ocaml/ocaml-lsp

- Makefile
- dune-project
- lsp/src/dune
- lsp/src/import.ml
- lsp/src/protocol.ml
- lsp/src/rpc.ml
- ocaml-lsp-server/src/dune
The recorded paths are now slightly different
> Update generated code

- README.md
so that instructions in the README actually work...
> opam pin commands are needed

- README.md
People are rightfully confused about the differences between the various LSP
servers we have around.
> Add comparison to other projects

- lsp/src/protocol.ml
- lsp/src/rpc.ml
- lsp/src/rpc.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-foldingRange.test.ts
The functionality is provided using merlin's outline call.
> Add support for textDocument/foldingRange

- lsp/src/import.ml
- lsp/src/protocol.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
* SignatureHelpOptions
* ParameterInformation
* SignatureInformation
> Add signature help lsp definitions

- lsp/src/import.ml
- lsp/src/protocol.ml
- lsp/src/protocol.mli
This is self explanatory. Also finds us some typos.
> Write mli for Lsp.Protocol

- .travis.yml
- Makefile
- ocaml-lsp-server.opam
- ocaml-lsp-server.opam.template
- ocaml-lsp-server/test/e2e/__tests__/textDocument-completion.test.ts
- ocaml-lsp-server/test/e2e/dune
- ocaml-lsp-server/test/e2e/package.json
> Run e2e tests on CI

- ocaml-lsp-server/src/dune
- ocaml-lsp-server/test/e2e/src/LanguageServer.ts
To be consistent with other ocaml tools.
> Rename ocaml-lsp-server to ocamllsp

- .gitmodules
- ocaml-lsp-server/src/dune
- ocaml-lsp-server/src/ocaml_lsp_server.ml
> Switch to Cmdliner

- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
ocamlmerlin-lsp is an old name
> Update logging section name

- lsp/src/protocol.ml
- lsp/src/protocol.mli
- lsp/src/rpc.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-codeAction.test.ts
> Add destruct code action

- lsp/src/import.ml
- lsp/src/protocol.ml
- lsp/src/protocol.mli
- lsp/src/rpc.ml
- lsp/src/rpc.mli
- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/document_store.ml
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
Currently this does nothing and just returns the same item
> CompletionItemResolve support

- lsp/src/protocol.ml
- lsp/src/protocol.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-definition.test.ts
This type is not present in the spec
> Remove definition location

- lsp/src/dune
- lsp/src/import.ml
- lsp/src/jsonrpc.ml
- lsp/src/jsonrpc.mli
- lsp/src/protocol.ml
- lsp/src/protocol.mli
- lsp/src/request.ml
- lsp/src/request.mli
- lsp/src/rpc.ml
- lsp/src/rpc.mli
- lsp/src/text_document_text.mli
- lsp/src/text_document_text.mll
- lsp/src/uri.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-codeAction.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-completion.test.ts
- ocaml-lsp-server/test/e2e/src/LanguageServer.ts
* Remove nuclide related fields
* Reflect optional fields more closely
> More faithful protocol implementation

- lsp/src/jsonrpc.ml
> Add jsonrpc to requests

- .travis.yml
- lsp/src/protocol.ml
- lsp/src/protocol.mli
I'm not setting any default values because the server might want to set the
preference here.
> Add 3.15.0 formatting options

- lsp/src/initialize.ml
- lsp/src/initialize.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
name/version parameters can now be supplied by client/server
> Support client/server version info

- README.md
- lsp/src/client_request.ml
- lsp/src/client_request.mli
- lsp/src/import.ml
- lsp/src/protocol.ml
- lsp/src/protocol.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
> Add support for selection range request

- lsp/src/codeAction.ml
- lsp/src/codeAction.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
isPreferredSupport was already present in the capabilities
> Add isPreferred field to code actions

- lsp/src/completion.ml
- lsp/src/completion.mli
- lsp/src/diagnostics.ml
- lsp/src/diagnostics.mli
- lsp/src/initialize.ml
- lsp/src/initialize.mli
- lsp/src/protocol.ml
- lsp/src/protocol.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
Also remove a legacy, facebook only field
> Add diagnostic tag support

- lsp/src/client_notification.ml
- lsp/src/initialize.ml
- lsp/src/initialize.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
* s/didSave/save
* Add correct defaults
Fix #93 as well
@Gbury could you check if this works for you?
> Fix TextDocumentSyncOptions

- lsp/src/initialize.ml
- lsp/src/protocol.ml
- lsp/src/protocol.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
@Ailrun could you check if this PR fixes the performance problems for you?
> disable resolution of completion items

- lsp/src/initialize.ml
> Better default capabilities for text document synchronization

- lsp/src/client_notification.ml
- lsp/src/client_notification.mli
- lsp/src/protocol.ml
- lsp/src/protocol.mli
- ocaml-lsp-server/src/document_store.ml
- ocaml-lsp-server/src/document_store.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
Hoping that this will help improve #107
> Implements didclose

- lsp/src/logger.ml
- ocaml-lsp-server/src/document_store.ml
This supposedly fixes #107, comes after discussion in #110 with @rgrinberg 
I'm creating the PR, for history, so that it'll be linked for the issue, but merging it right away this should be very straightforward
> use Table.replace instead of Table.set

- ocaml-lsp-server/src/ocaml_lsp_server.ml
> quick fix for failures in code actions

- lsp/src/uri.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-formatting.test.ts
File proto is set to file:// and conditionally added / on non cygwin
systems only
> Fixes e2e tests on Windows.

- lsp/src/dune
- lsp/src/rpc.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
Replaces >>= with the new syntax introduced in 4.08
> Use future_syntax

- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
> Add codeLensProvider to ServerCapabilities

- ocaml-lsp-server/src/fmt.ml
> better message for formatting missing binary.

- README.md
You don't have to use a resolution for esy to work
> Simpler esy setup

- ocaml-lsp-server/test/e2e/__tests__/Lifecycle.test.ts
- ocaml-lsp-server/test/e2e/__tests__/Request.Debug.test.ts
- ocaml-lsp-server/test/e2e/__tests__/TextDocument.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-codeAction.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-codeLens.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-completion.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-definition.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-documentHighlight.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-documentSymbol.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-foldingRange.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-formatting.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-hover.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-references.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-rename.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-selectionRange.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-typeDefinition.test.ts
- ocaml-lsp-server/test/e2e/src/LanguageServer.ts
> Windows tests tweaks

- lsp/src/import.ml
- lsp/src/text_document.ml
- lsp/src/text_document.mli
- ocaml-lsp-server/src/bin.ml
- ocaml-lsp-server/src/bin.mli
- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/document.mli
- ocaml-lsp-server/src/fmt.ml
- ocaml-lsp-server/src/fmt.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/TextDocument.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-codeAction.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-codeLens.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-completion.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-definition.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-documentHighlight.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-documentSymbol.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-foldingRange.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-formatting.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-hover.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-references.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-rename.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-selectionRange.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-typeDefinition.test.ts
If it's missing, the error will be reported as a diagnostic.
> Add diagnostic for ocamlmerlin_reason

- lsp/src/dune
- lsp/src/rpc.ml
- lsp/src/rpc.mli
- ocaml-lsp-server/src/dune
- ocaml-lsp-server/src/ocaml_lsp_server.ml
> Use fibers to implement the loop in Rpc.

- README.md
When we want to use the lsp, we must see `ocaml-lsp-server/src/dune` to check the command name at present.
This PR adds the command name to `README.md`.
> add command name

- .gitignore
- README.md
- ocaml-lsp-server.opam
Added steps I had to perform on clean repo as a short contribution guide.
Also gitignored `_opam` to support local switch setup ~and added `cmdliner` to dependencies as it was missing~.
> Add short contribution "guide"

- dune-project
- lsp.opam
- ocaml-lsp-server.opam
* Don't use :dev dependencies
* Add more authors
* Menhir isn't an lsp dependency
> Update opam metadata

- lsp/src/scheduler.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- vendor/fiber/fiber.ml
- vendor/fiber/fiber.mli
Scheduling is now done completely outside the library.
> Update to latest version of fiber

- dune-project
- ocaml-lsp-server.opam
> This dependency is vendored

- dune-project
- lsp.opam
- lsp/src/dune
- lsp/src/uri0.ml
- ocaml-lsp-server.opam
This seems to break windows
@mnxn could you confirm this fixes things for you?
@giltho  i've reverted things in a gentle way so it's easier to introduce the
changes back.
> Revert switch to URI

- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
To support this PR:
https://github.com/ocamllabs/vscode-ocaml-platform/pull/209
> Add support for ocaml.interface language id

- ocaml-lsp-server/src/ocaml_lsp_server.ml
This is useful to complete methods
> Trigger completion on #

- ocaml-lsp-server/src/ocaml_lsp_server.ml
Somehow it was dropped again :/
> Add foldin range provider

- ocaml-lsp-server/src/ocaml_lsp_server.ml
The current code lens functionality only provides inferred types. Those
aren't very useful for mli files
@Khady I believe we agreed on this earlier
> Disable code lens for mli/rei files

- ocaml-lsp-server/src/ocaml_lsp_server.ml
Code to convert merlin definition results to an LSP location should be
shared between request handlers.
> Factor out position handling code

- ocaml-lsp-server/src/ocaml_lsp_server.ml
This function is available in Stdune
> Remove min_by_opt

- ocaml-lsp-server/test/e2e/__tests__/TextDocument.test.ts
- ocaml-lsp-server/test/e2e/package.json
These tests weren't being terminated correctly
> Fix text document tests

- lsp/src/import.ml
- lsp/src/io.ml
- lsp/src/jsonrpc.ml
- lsp/test/jsonrpc_test.ml
- lsp/test/server_test.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
This is what we prefer because the Yojson is too complicated
> Refer to Yojson by Json

- ocaml-lsp-server/src/compl.ml
- ocaml-lsp-server/src/compl.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
Implements #215. 
How it looks like (with markdown support):
> Show docs on code-completion request

- ocaml-lsp-server/src/ocaml_lsp_server.ml
The previous implementation would still run Bin.which on every single
change. Now all work is debounced.
> Make send diagnostics lazier

- .github/workflows/build-and-test.yml
- Makefile
- ocaml-lsp-server.opam
- ocaml-lsp-server.opam.template
- only run tests on latest platforms
- make sure code is formatted
> Improve ci test config

- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/position.ml
> Do no crash on invalid positions

- ocaml-lsp-server/src/compl.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-completion.test.ts
> Fix completion bug #252

- ocaml-lsp-server/src/ocaml_lsp_server.ml
This action does not make sense in interface files
> Disable destruct in intf files

- ocaml-lsp-server/src/destruct_lsp.ml
- ocaml-lsp-server/src/destruct_lsp.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
We choose the name destruct_lsp because toplevel destruct is taken by merlin
> Move destruct to own module

- lsp/src/scheduler.ml
Remove unnecessary packed_active_timer type
This slightly changes the semantics by making sure the old scheduled callback is
aware of the cancellation before the new one is launched.
> Simplify timer handling

- lsp/src/rpc.ml
- lsp/src/rpc.mli
- lsp/src/scheduler.ml
- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/document.mli
- ocaml-lsp-server/src/document_store.ml
- ocaml-lsp-server/src/document_store.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
Close timers on shutdown.
It seems like the test errors are caused by the server trying to send
diagnostics after shutdown. This PR doesn't fix the issue entirely, I'll send
additional PR's to fix this.
> Cleaner shutdown

- fiber-test/fiber_test.ml
- fiber-unix/src/fiber_detached.ml
- fiber-unix/src/fiber_detached.mli
- fiber-unix/src/scheduler.ml
- fiber-unix/src/scheduler.mli
- fiber-unix/test/fiber_detached_tests.ml
- fiber-unix/test/scheduler_tests.ml
- jsonrpc-fiber/test/jsonrpc_fiber_tests.ml
- lsp-fiber/src/fiber_io.ml
- lsp-fiber/src/rpc.ml
- lsp-fiber/test/server_test.ml
- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/state.ml
- ocaml-lsp-server/src/state.mli
- vendor/fiber/fiber.ml
- vendor/fiber/fiber.mli
Implement task detaching entirely using fibers.
> Remove Scheduler.detach

- lsp-fiber/test/dune
- lsp-fiber/test/lsp_fiber_test.ml
Same test but the output is now readable
> Switch lsp tests to ppx_expect

- ocaml-lsp-server/src/compl.ml
- vendor/stdune/string.ml
- vendor/stdune/string.mli
Do the entire operation in a single pass with the help of String.rfrom
> Simplify prefix_of_position

- jsonrpc-fiber/src/jsonrpc_fiber.ml
- jsonrpc-fiber/test/jsonrpc_fiber_tests.ml
- lsp-fiber/test/lsp_fiber_test.ml
Fix stopping the jsonrpc server
> Do not double stop

- lsp/src/text_document.ml
- lsp/src/text_document.mli
- ocaml-lsp-server/src/compl.ml
- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/document.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
It does not seem to be safe to do these operations concurrently to
merlin
> Create documents in merlin thread

- jsonrpc-fiber/src/import.ml
- lsp-fiber/src/import.ml
- lsp/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
It's not thread safe and offers no convenience to make up for it.
> Remove uses of str_formatter

- fiber-test/fiber_test.ml
Makes the tests a little more reliable
> Do not reuse fiber scheduler between tests

- lsp-fiber/src/rpc.ml
- lsp-fiber/src/rpc.mli
- lsp-fiber/test/lsp_fiber_test.ml
- ocaml-lsp-server/src/custom_requests/req_infer_intf.ml
- ocaml-lsp-server/src/custom_requests/req_infer_intf.mli
- ocaml-lsp-server/src/custom_requests/req_switch_impl_intf.ml
- ocaml-lsp-server/src/custom_requests/req_switch_impl_intf.mli
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
This PR makes ocamllsp server serve requests concurrently. Almost all requests
are serialized by using merlin, but it does give us the opportunity to read
cancellation notifications.
> Concurrent request handling

- lsp-fiber/test/lsp_fiber_test.ml
In before I add cancellation tests
> [test] [lsp] refactor tests

- .github/workflows/build-and-test.yml
- Makefile
* test should run all tests.
* all test logic should live in the makefile rather than the ci script
* fix typo in test target (test-template)
* add promote/check targets
* do not set dune root. it should respect workspace files above the repo dir
> Makefile & CI tweaks

- .github/workflows/build-and-test.yml
> Run unit tests only on latest OCaml version

- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/inference.ml
- ocaml-lsp-server/test/e2e/__tests__/ocamllsp-inferIntf.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-declaration.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-definition.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-diagnostics.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-documentSymbol.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-hover.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-signatureHelp.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-typeDefinition.test.ts
- ocaml-lsp-server/test/e2e/package.json
- ocaml-lsp-server/test/e2e/src/LanguageServer.ts
- ocaml-lsp-server/test/e2e/yarn.lock
Follow up of #352
This updates all of the dependencies and fixes the unit tests that broke with the update
> Update NPM dependencies

- vendor/fiber/fiber.ml
> [Fiber] allow concurrent writes

- jsonrpc/src/import.ml
- jsonrpc/src/jsonrpc.ml
Should make it simpler to debug issues for ourselves and other users of this
library.
> Print jsonrpc errors

- lsp/src/uri0.ml
- lsp/src/uri_lexer.mli
- lsp/src/uri_lexer.mll
- lsp/test/uri_tests.ml
- ocaml-lsp-server/src/inference.ml
> Fix URI handling on Windows

- lsp/bin/specifications/specification-3-16.md
- lsp/src/types.ml
- lsp/src/types.mli
Should fix https://github.com/ocamllabs/vscode-ocaml-platform/issues/587
> fix crash when trace is set to messages

- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/inference.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-hover.test.ts
And also fix the ensuing bug in pretty printing of signatures
> Enable short paths by default

- ocaml-lsp-server/src/dune.ml
- ocaml-lsp-server/src/dune.mli
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/state.ml
- ocaml-lsp-server/src/state.mli
We attempt to find dune and check that it's recent enough for RPC
functionality. No new functionality is added, this PR is mostly to avoid
conflicts for future PR's.
> Start dune and detect version

- ocaml-lsp-server/src/ocaml_lsp_server.ml
noticed this notif, which doesn't do anything
> remove unnecessary log

- lsp-fiber/src/fiber_io.ml
- lsp/src/import.ml
- lsp/src/uri0.ml
- lsp/src/uri0.mli
- ocaml-lsp-server/src/diagnostics.ml
- ocaml-lsp-server/src/diagnostics.mli
- ocaml-lsp-server/src/dune
- ocaml-lsp-server/src/dune.ml
- ocaml-lsp-server/src/dune.mli
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/state.ml
- ocaml-lsp-server/src/state.mli
- ocaml-lsp-server/test/e2e/__tests__/textDocument-diagnostics.ts
Still WIP, but gets us pretty far.
The main complication is handling the mismatch between how LSP and dune handle
notifications. LSP allows us updating notifications for a document in batch,
which means that we need to know the last notifications unrelated to dune, so
that we only update the dune section.
> Dune RPC Integration

- CHANGES.md
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-rename.test.ts
is based on #399 ; it's best if we merge that PR first
https://user-images.githubusercontent.com/16353531/126861794-3922c017-2585-4d0f-9672-def12ef35486.mov
> Fix: correctly rename var when it's punned

- CHANGES.md
- ocaml-lsp-server/src/code_actions/action_add_rec.ml
- ocaml-lsp-server/src/code_actions/action_add_rec.mli
- ocaml-lsp-server/src/compl.ml
- ocaml-lsp-server/src/compl.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-codeAction.test.ts
Add an "add missing rec keyword" action. Closes #319.
> Action add-rec

- CHANGES.md
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
> misc: clean up import.ml, ocaml_lsp_server.ml, changelog

- CHANGES.md
- lsp/src/text_document.ml
- lsp/src/text_document.mli
- ocaml-lsp-server/src/compl.ml
- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/document.mli
- ocaml-lsp-server/src/inference.ml
- ocaml-lsp-server/src/lazy_fiber.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
@copy ~~I did not touch the debouncing yet, but I did hopefully speed up the updates~~ I did address one issue with the debouncing. Let me know if this is any better for you.
> Doc update performance

- dune
- ocaml-lsp-server/vendor/dune
> Use %{project_root} instead of %{workspace_root}

- dune
- ocaml-lsp-server/src/ocaml_lsp_server.ml
@jfeser I assume this was omitted by accident?
> Add Action_add_rec to server capabilities

- .github/workflows/build-and-test.yml
> Restore Windows CI

- CHANGES.md
- fiber-unix/src/dune
- fiber-unix/src/scheduler.ml
- fiber-unix/src/worker.ml
- fiber-unix/src/worker.mli
@hcarty mind testing this out?
> Fix ppx process running

- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/document.mli
Make sure the syntax is known before constructing the document.
> Better handling of invalid syntax

- CHANGES.md
- ocaml-lsp-server/src/folding_range.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-foldingRange.test.ts
Adds folding support for 
- record expressions and patterns
- match expressions, case patterns, case expressions
TODO: 
@tatchi if you'd like to have a look
> More more folding

- ocaml-lsp-server/src/dune.ml
let the user know when errors occur and include some useful information
in them
> fix(dune): improve error handling

- ocaml-lsp-server/src/ocaml_lsp_server.ml
Lev_fiber.Io.{stdin,stdout,stderr} are now available
> refactor: simplify by using lev_fiber builtins

- dune-project
- ocaml-lsp-server.opam
- ocaml-lsp-server/bin/dune
- ocaml-lsp-server/bin/main.ml
an additional dependency that doesn't buy anything
> chore: get rid of cmdliner

- ocaml-lsp-server/src/ocamlformat_rpc.ml
> fix: async io for ocamlformat-rpc-lib

- CHANGES.md
> revert to 4 13 again

- lsp/src/server_request.ml
* encode unknown requests
* do not provide null for missing parameters. Just omit the field
altogether
> fix(lsp): encode all server requests correctly

- dune
Companion to https://github.com/ocaml/ocaml-lsp/commit/3e76bbb83a1dc6d0f102908c1bd5e6fabdc12f57 and rgrinberg/lev#3.
> Fix lev compilation flags

- Makefile
- jsonrpc-fiber/test/jsonrpc_fiber_tests.ml
> use sexplib0 v0.14.0

- ocaml-lsp-server/src/dune.ml
Don't log the same polling errors over and over.
> fix(rpc): quiet down dune registry polling

- dune-project
- lsp.opam
ps-id: 790849fd-7677-4e80-90ff-12d5d6fef9ee
> chore: fix opam files

- lsp-fiber/test/lsp_fiber_test.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e-new/start_stop.ml
ps-id: 6a08440a-71bc-4c3d-9896-9ede9135837c
> chore: update lev

- CHANGES.md
ps-id: b02973fa-e5d6-4c67-b760-7dc11efed6b0
> chore: fix formatting

- .github/workflows/build-and-test.yml
- .github/workflows/nix.yml
- Makefile
- fmt.nix
- ocamlformat.nix
- shell.nix
ps-id: 394ae13f-caa3-47b4-a4e9-f126ca48e770
> chore(ci): format with nix

- ocaml-lsp-server/src/ocaml_lsp_server.ml
ps-id: bd2bdce5-a6e9-46b4-b0e8-98a94d6f45ae
> chore: remove outdated todo

- ocaml-lsp-server/src/dune.ml
- ocaml-lsp-server/src/merlin_config.ml
- ocaml-lsp-server/src/ocamlformat_rpc.ml
- submodules/lev/.gitrepo
- submodules/lev/dune-project
- submodules/lev/lev-fiber-csexp/src/lev_fiber_csexp.ml
- submodules/lev/lev-fiber-csexp/src/lev_fiber_csexp.mli
- submodules/lev/lev-fiber-csexp/test/lev_fiber_csexp_rpc_tests.ml
- submodules/lev/lev-fiber.opam
- submodules/lev/lev-fiber/src/lev_fiber.ml
- submodules/lev/lev-fiber/src/lev_fiber.mli
- submodules/lev/lev-fiber/test/reader_writer.ml
- submodules/lev/lev/src/lev_stubs.c
- submodules/lev/lev/test/lev_tests_unix.ml
subrepo:
subdir:   "submodules/lev"
merged:   "85150ba4"
upstream:
origin:   "https://github.com/rgrinberg/lev"
branch:   "master"
commit:   "85150ba4"
git-subrepo:
version:  "0.4.1"
origin:   "???"
commit:   "???"
ps-id: de96763b-de9d-45e5-8f06-a03166501643
> git subrepo pull submodules/lev

- CHANGES.md
- ocaml-lsp-server/vendor/merlin/.gitrepo
- ocaml-lsp-server/vendor/merlin/src/kernel/mtyper.ml
- ocaml-lsp-server/vendor/merlin/src/kernel/mtyper.mli
- ocaml-lsp-server/vendor/merlin/src/ocaml/driver/pparse.ml
subrepo:
subdir:   "ocaml-lsp-server/vendor/merlin"
merged:   "a66e05c3"
upstream:
origin:   "https://github.com/rgrinberg/merlin"
branch:   "master"
commit:   "a66e05c3"
git-subrepo:
version:  "0.4.1"
origin:   "???"
commit:   "???"
_
ps-id: 311ebd48-4e01-46c3-8039-91f79045265b
> git subrepo clone https://github.com/rgrinberg/merlin ocaml-lsp-server/vendor/merlin

- lsp/src/types.ml
- lsp/src/types.mli
- ocaml-lsp-server/src/array_view.ml
- ocaml-lsp-server/src/array_view.mli
- ocaml-lsp-server/src/document_store.ml
- ocaml-lsp-server/src/document_store.mli
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/range.ml
- ocaml-lsp-server/src/range.mli
- ocaml-lsp-server/src/semantic_highlighting.ml
- ocaml-lsp-server/src/semantic_highlighting.mli
- ocaml-lsp-server/test/e2e-new/dune
- ocaml-lsp-server/test/e2e-new/semantic_hl_data.ml
- ocaml-lsp-server/test/e2e-new/semantic_hl_tests.ml
- ocaml-lsp-server/test/e2e-new/test.ml
There're still improvements to be made but wanted to get this public in case I'll get some feedback. 
Having some tests would be good. 
Would love some feedback on editing latency -- if you feel experience worsened. 
We can make this feature opt-in if people prefer that, at least until the feature is more stable. 
`Tokens` module could use a vector implementation rather than a `list ref` to be more efficient, I think. 
----
----
> Add support for semantic highlighting

- lsp/bin/dune
- lsp/bin/metaModel.json
- lsp/bin/metamodel.ml
- lsp/bin/metamodel.mli
- lsp/bin/test_metamodel.ml
in preparation for 3.17
ps-id: E0AE7554-7060-4327-854C-5BABF6DB7742
> feature(lsp): add metamodel parser

- flake.lock
ps-id: fa893f3f-03ce-4f49-a13b-06063cb87a79
> chore: update nix

- README.md
> Allow copy-and-paste of contributing instructions

- CHANGES.md
ps-id: 3c947f69-ce87-4e54-a31f-e739abc642ae
> chore: prepare 1.14.0

- flake.lock
- flake.nix
ps-id: 577aaea5-6516-4fb9-b31c-ab17288fae71
> chore(nix): update flakes

- ocaml-lsp-server/src/compl.ml
ps-id: 49a952ff-4c54-4210-8795-6a44d4c38311
> fix: respect deprecated completion capability

- .github/workflows/build-and-test.yml
- .gitmodules
- CHANGES.md
- Makefile
- dune-project
- ocaml-lsp-server.opam
- submodules/lev/.github/workflows/workflow.yml
- Revert "chore: prepare 1.15.0"
- Revert "upgrade to merlin with support for ocaml 5, upgrade olsp opam file to ocaml 5"
- Revert "Add missing declaration for functions"
> revert releases

- lsp/test/text_document_tests.ml
ps-id: d33da531-d5a7-4df7-aac9-cff224ee69e9
> test(lsp): improve editing tests

- flake.lock
> chore: update flakes

- flake.nix
this makes it possible for casual users to use this flake without
pulling opam2nix
> chore(nix): simplify default flake output

- lsp/src/text_document.ml
> chore(lsp): fix incorrect comment

- lsp/src/string_zipper.ml
- lsp/src/string_zipper.mli
- lsp/src/text_document.ml
- lsp/src/text_document.mli
> feature(lsp): low level zipper api

- CHANGES.md
- ocaml-lsp-server/src/dune.ml
Signed-off-by: nojebar <nicolas.ojeda.bar@lexifi.com>
> fix(dunerpc): normalize case under Windows

- .github/workflows/build-and-test.yml
> coverage: don't allow failure in workflow

- CHANGES.md
(This will alert the Windows-using users that they are concerned by #1080.)
> Add 'Windows' to CHANGES entry for #1080

- lsp/src/client_notification.ml
- lsp/src/client_notification.mli
- lsp/src/lsp.ml
- lsp/src/progress.ml
- lsp/src/progress.mli
- lsp/src/server_notification.ml
- lsp/src/server_notification.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/progress.ml
- ocaml-lsp-server/src/progress.mli
> feature(lsp): allow progress notifications from client

- lsp/bin/dune
> fix: dependency on metamodel tests

- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/signature_help.ml
> refactor: cleanup signature help

- ocaml-lsp-server/src/merlin_config.ml
> fix: killing merlin on windows

- ocaml-lsp-server/test/e2e-new/dune
- ocaml-lsp-server/test/e2e-new/for_ppx.ml
- ocaml-lsp-server/test/e2e-new/test.ml
- ocaml-lsp-server/test/e2e-new/with_ppx.ml
> test: demonstrate that ppx works

- ocaml-lsp-server/src/ocaml_lsp_server.ml
> chore: remove some pointless qualification

- dune-project
- ocaml-lsp-server.opam
> chore: update constraints

- CHANGES.md
> chore: prepare 1.16.0

- CHANGES.md
> chore: prepare 1.16.1

- CHANGES.md
- ocaml-lsp-server/src/semantic_highlighting.ml
- ocaml-lsp-server/test/e2e-new/semantic_hl_tests.ml
> Disable semantic highlighting unit () as enum member

- CHANGES.md
> chore: better formatting in CHANGES

- ocaml-lsp-server/test/e2e-new/dune
> fix(test): correctly qualify pp dep

- flake.nix
> chore: move dune-release to own shell

- ocaml-lsp-server/docs/ocamllsp/config.md
Updates `config.md` to reflect the changes after #1159.
> config.md: update to include inlay hints

- ocaml-lsp-server/src/progress.ml
- ocaml-lsp-server/src/progress.mli
> refactor: remove some dead code

- ocaml-lsp-server/test/e2e-new/dune
> test: add missing dependency

- ocaml-lsp-server/src/dune
- ocaml-lsp-server/test/e2e-new/dune
> chore: add missing unix dependency

- flake.nix
> chore(nix): remove stdune dep from lsp

- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/position.mli
> chore: remove re-export of ordering from stdune

- ocaml-lsp-server/test/e2e-new/dune
- ocaml-lsp-server/test/e2e-new/for_pp.sh
> test: remove for_pp script

- flake.nix
> chore(nix): remove some duplication

- flake.nix
> chore(nix): remove pp from deps

- flake.nix
> chore(nix): remove octavius

- flake.nix
> chore(nix): remove some copy pasting

- lsp/bin/import.ml
- lsp/bin/ocaml/ml.mli
- lsp/bin/ocaml/ocaml.ml
- lsp/bin/ocaml/w.mli
> refactor: limit [Stdune] usage in code gen

- dune-project
- flake.nix
- ocaml-lsp-server.opam
> chore: remove uutf from deps

- lsp/test/string_zipper_tests.ml
> test: try to repro drop_until bug

- .github/workflows/nix.yml
- flake.nix
one that doesn't install a bunch of unrelated stuff just to format
> chore(nix): better formatting job

- .github/workflows/nix.yml
- flake.nix
> chore(nix): simplify test job

- flake.nix
ocamlformat and dune-release nix shells don't need overlays
> chore(nix): no overlays for ocamlformat/release

- .ocamlformat
- dune-project
- flake.lock
- flake.nix
> chore: upgrade to ocamlformat 0.26.2

- Makefile
- ocaml-lsp-server/test/e2e/__tests__/ocamllsp-hoverExtended.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-codeLens.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-declaration.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-documentHighlight.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-formatting.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-hover.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-references.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-rename.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-selectionRange.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-signatureHelp.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-typeDefinition.test.ts
- ocaml-lsp-server/test/e2e/package.json
- ocaml-lsp-server/test/e2e/yarn.lock
> test: use snapshots everywhere

- ocaml-lsp-server/src/code_actions/action_add_rec.ml
> chore: simplify some qualification

- lsp/bin/cinaps.ml
- lsp/bin/metamodel/metaModel.json
- lsp/bin/metamodel/metamodel.ml
- lsp/bin/ocaml/ocaml.ml
- lsp/bin/typescript/ts_types.ml
- lsp/bin/typescript/ts_types.mli
- lsp/src/types.ml
- lsp/src/types.mli
- ocaml-lsp-server/src/code_actions/action_add_rec.ml
- ocaml-lsp-server/src/code_actions/action_mark_remove_unused.ml
- ocaml-lsp-server/src/diagnostics.ml
- ocaml-lsp-server/src/dune.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/signature_help.ml
- ocaml-lsp-server/test/e2e-new/action_mark_remove.ml
- ocaml-lsp-server/test/e2e-new/with_ppx.ml
> feature: update lsp spec

- lsp/src/uri0.ml
- lsp/src/uri0.mli
- lsp/src/uri_lexer.mli
- lsp/src/uri_lexer.mll
- lsp/test/uri_tests.ml
> feature(lsp): add basic query support to uri's

- dune
> chore: disable warning 58 for now

- flake.nix
> chore(nix): add back test deps for dev

- ocaml-lsp-server/src/code_actions.ml
> Minor patch for Jump codeactions

- ocaml-lsp-server/src/workspace_symbol.ml
Restore compatibility with merlin main.
> Handle new kind of outline symbol
