- ocaml-lsp-server/src/ocaml_lsp_server.ml
Before that this used merlin's `Logger` module while `lsp` used
`Lsp.Logger` and thus we didn't see `lsp` section when running server.
> Use Lsp.Logger

- lsp/src/logger.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/src/LanguageServer.ts
This patch series:
- improves the way command line arguments are handled (using `Arg`)
- add an option to specify the file (better than the environment variable)
- make sure the logging output is flushed
> Logging improvements

- lsp/src/protocol.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
* Add triggerCharacter field to completionContext
* commitCharacters field to result
@andreypopp I see that we're using `[@default None]` for these optional fields.
What's the difference between this and `[@yojson.option]`?
> More completion related fields in LSP

- lsp/src/protocol.ml
- lsp/src/rpc.ml
The spec allows the Id to be an integer or a string
Fix #35
> Allow for string id's

- dune-project
- lsp.opam
- lsp/src/import.ml
- ocaml-lsp-server.opam
- ocaml-lsp-server/src/ocaml_lsp_server.ml
As we depend on OCaml >= 4.06 we don't need this package.
> Remove dependency on result package

- lsp/src/protocol.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
In this PR I'd like to add support for code actions in LSP:
> LSP - Code Actions

- ocaml-lsp-server/src/ocaml_lsp_server.ml
> Do not terminate server after exceptions

- ocaml-lsp-server/src/ocaml_lsp_server.ml
In the plaintext hover result the docs come first, and nothing separates
it from the type.
This is visible when used through Vim/ALE in a terminal, where you'd get
something like this:
```
(**  [String.map f s] applies function [f] in turn to all the
characters of [s] (in increasing index order) and stores the
results in a new string that is returned.
@since 4.00.0  *)(char -> char) -> string -> string
```
Put the doc last: this is consistent with the markdown format, and has a newline when not empty.
> Plaintext hover result: separate docs from type

- lsp/src/client_request.ml
- lsp/src/client_request.mli
- lsp/src/codeAction.ml
- lsp/src/protocol.ml
- lsp/src/protocol.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
Simply adds `workspace/executeCommand` to the lsp lib.
Also formats the part of codeAction.ml using `make fmt`
> LSP: executeCommand

- README.md
- dune-project
- lsp/src/import.ml
- ocaml-lsp-server.opam
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/ocamlformat.ml
- ocaml-lsp-server/src/ocamlformat.mli
- ocaml-lsp-server/test/e2e/__tests__/textDocument-formatting.test.ts
This PR implements `textDocument/formatting` with a wrapper module to `ocamlformat`.
It finds `ocamlformat` from the current PATH and runs it at the current directory `ocamllsp` is running. Note that I didn't add any facility to find the nearest `.ocamlformat`.
`textDocument/{rangeFormatting, onTypeFormatting}` is not yet implemented. Once https://github.com/ocaml-ppx/ocamlformat/pull/1188 comes into reality, we can easily extend this implementation to support them.
> Implement textDocument/formatting

- lsp/src/jsonrpc.ml
- lsp/src/jsonrpc.mli
- lsp/src/rpc.ml
Fixes #101 
However, I am not entirely sure that this is the right answer.
For example when handling client requests, should I only try and catch the exceptions in the handler or in the whole process of responding. Meaning, should the `try..with` be surrounding the whole block (like what I did) or just the 
```ocaml
handler.on_request rpc state client_capabilities req
```
What if the exception arises after a response has already been sent ? Right now this can't really happen, but if we ever add things to do after the `send_response`...
But then, if I only surround the handler, I don't know what I should return by default.
Conclusion : I think this is the right answer, but there may be slightly different choices to make
> Try and recover on InternalError

- lsp/src/rpc.ml
- lsp/src/rpc.mli
- ocaml-lsp-server/src/document_store.ml
- ocaml-lsp-server/src/document_store.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
Changed the signature of request to return either a success (store * resp) or a Response.Error
The server should always answer requests, even in case of error, it should return an error response.
> Always return something on request

- lsp/src/protocol.ml
- lsp/src/protocol.mli
[The specification][spec] states that only a single edit should be supplied. Multiple edits can be embedded inside `WorkspaceEdit.t`.
I realise that the lsp package doesn't currently have support for server requests, so fixing this may not be a high priority. I had a quick play around with bodging in support locally, and found this bug as a result.
[spec]: https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#workspace_applyEdit
> Fix incorrect type for workspace/applyEdit request

- lsp/src/logger.ml
- lsp/src/logger.mli
- lsp/src/rpc.ml
- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
This PR makes the server to send log outputs to client through `window/logMessage`.
This will make debugging far easier within VSCode or other editors.
To match [the LSP spec](https://microsoft.github.io/language-server-protocol/specification#window_showMessage) and avoid an infinite loop [while logging about request sending/receiving](https://github.com/ocaml/ocaml-lsp/blob/master/lsp/src/rpc.ml#L18), this PR also introduces a type `Logger.Title.t`.
> Logging through LSP

- lsp/src/initialize.ml
- lsp/src/initialize.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-selectionRange.test.ts
Closes #100.
This PR implements `textDocument/selectionRange`.
This is still WIP:
> Implement textDocument/selectionRange

- ocaml-lsp-server/src/ocaml_lsp_server.ml
Looks like this was (accidentally?) removed in
7860a87689b5bdd3309445831227e32995c1d8b5.
Fixes #124.
> Add documentFormattingProvider to server capabilities

- lsp/src/scheduler.ml
- lsp/src/scheduler.mli
- lsp/test/dune
- lsp/test/fiber_thread_test.ml
- lsp/test/server_test.ml
@jfeser @giltho, this is a preview of the scheduler required to make #151 work with fibers.
In particular, it contains two comoponents:
* A way to run computations in separate threads. We will be using this for async
IO
* A timer mechanism to implement batched updates. This implementation slightly
differs with #151 by having the "waker" run in a separate thread. Otherwise, this
snippet:
```ocaml
Option.iter !next_time ~f:(fun t ->
Thread.delay (t -. Unix.gettimeofday ()));
```
is problematic. What happens when a new timer that's due before `!next_time` is scheduled?
Some initial review would be helpful.
> Preview of fiber based scheduler

- lsp/src/jsonrpc.ml
- lsp/src/jsonrpc.mli
An abstract implementation of the jsonrpc state machine. Correctly handles out
of order requests.
I'm trying to upstream `fork_and_race` first. So for now it's just a dummy
implementation. The funcrorization over `Chan` is useful while we still don't
have a Fiber based stream.
> Jsonrpc.Session

- .ocamlformat
- lsp/bin/markdown/markdown.mli
- lsp/bin/ocaml/ocaml.ml
- lsp/src/scheduler.ml
After all, from 0.14.2, it seems to get the same behavior with the same configuration as before 0.14.0.
> Upgrade to ocamlformat 0.14.2

- lsp/src/dune
Unnecessary since we don't support 4.02 anyway
> Remove cruft

- ocaml-lsp-server/test/e2e/__tests__/textDocument-formatting.test.ts
In the process of trying to reproduce https://github.com/ocamllabs/vscode-ocaml-platform/issues/223 I wrote this test. Apparently the problem was on my side. But you might want to keep the test.
> Test support of ocamlformat-ignore

- ocaml-lsp-server/src/ocaml_lsp_server.ml
Set `ocaml-lsp` as the source of the diagnostics. It is convenient when multiple tools can provide diagnostics. For example if I have a build task in addition to the lsp server. With this addition I can see which errors are coming from ocamllsp and which are coming from my build task.
> Set ocaml-lsp as source of diagnostics

- dune-project
- ocaml-lsp-server.opam
- ocaml-lsp-server/src/dune
- ocaml-lsp-server/src/main.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/version.ml
- ocaml-lsp-server/src/version.mli
The version is accessible in two different ways:
* traditionally via the ocmmandline `$ ocamllsp --version`
* inside the initialize result sent by the server
> Add binary version

- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/position.ml
- ocaml-lsp-server/src/position.mli
- ocaml-lsp-server/src/range.ml
Dummy positions are now turned into ranges that span the first line of
the file.
There's also a warning if merlin returns a dummy position as the
definition source.
> Handle dummy positions

- .github/workflows/build-and-test.yml
- dune-project
- ocaml-lsp-server.opam
- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/document.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-hover.test.ts
The `hover` request is hard-coded to always specify a language type of `ocaml`, but it's actually sending Reason code over in the Reason case - but the language specifier is always `ocaml`.
This selects the language id conditionally based on the syntax of the document.
Fixes #206
> Fix #206: Select markdown language id based on document syntax

- lsp/src/client_request.ml
- lsp/src/client_request.mli
- lsp/src/rpc.ml
- lsp/src/server_request.ml
- lsp/src/server_request.mli
The signature of yojson_of_result was:
val yojson_of_result : 'a t -> 'a -> Json.t option
This isn't correct because the result cannot be None.
This PR makes the return type Json.t and returns null for previous None
values.
> Response of types of requests aren't optional

- lsp/src/scheduler.ml
- lsp/src/scheduler.mli
- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/document.mli
- ocaml-lsp-server/src/document_store.ml
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
This PR introduces an individual timer for every document. The advantage
of this are twofold:
* It allows us to configure the delay per document.
* When we close a document, we can cancel outstanding timed tasks.
> Per document timer

- .gitmodules
- ocaml-lsp-server/src/doc_to_md.ml
- ocaml-lsp-server/src/doc_to_md.mli
- ocaml-lsp-server/src/dune
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-hover.test.ts
A little reworked version of #104. Differences:
- vendored `omd` and `octavius`
Note: There was a problem with vendoring `omd` because it is being rewritten: the last published version on opam does not use dune (hence, cannot be vendored with dune) and the current version lacks necessary functionality. So I rewrote the last published version of omd to dune and vendored that repo.
- I removed grouping of various tags for now (in @jorisgio's implementation, params where combined under "Params" header, etc.). I thought it is better if we agree on the interface first before doing something like that.
The new version:
- added a test 
~~Note: currently, the test I wrote is failing, and I cannot figure why. The produced result matches the expected one in `console.log`.~~
> Convert doc comments to markdown

- lsp/src/client_request.ml
- lsp/src/client_request.mli
- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/document.mli
- ocaml-lsp-server/src/fmt.ml
- ocaml-lsp-server/src/fmt.mli
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
We don't actually support any functionality, it's just a new language type. This
is a pre-req for ml/mli switching however.
> Add support for ocamllex/menhir syntax

- README.md
- lsp/src/client_request.ml
- ocaml-lsp-server/src/compl.ml
- ocaml-lsp-server/src/compl.mli
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/completionItem-resolve.test.ts
Implements `completionItem/resolve` for lazy fetch of docs on code completion.
`textDocument/completion` seems to take now 2-4 times less time. 
Due to the merlin's API, we need to provide it with a document and a position for it to be able to fetch docs. I modify the given document to "fake" the completion. (is there a simpler/cheaper solution?)
I will rebase when we settle on the solution. 
The PR also seems to fix (merlin's?) bug: currently, ocaml-lsp on `Hashtbl.Make<cursor>` shows an empty documentation, but with the new implementation there is documentation.
> Implements "completionItem/resolve"

- lsp/test/dune
- ocaml-lsp-server/src/compl.ml
- ocaml-lsp-server/test/e2e/__tests__/completionItem-resolve.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-completion.test.ts
- ocaml-lsp-server/test/e2e/src/LanguageServer.ts
Fixes #51 
Prefix lookup is now taking infix operator characters into account, and prefix is used to generate a textedit that overrides it.
> fix Infix completion

- README.md
When going through the contributor section of the readme, installing the dependencies after creating the switch with `opam install` didn't work for me. Adding the `--with-test` flag during the creation of the switch worked for me.
As @rgrinberg [said in discord](https://discord.com/channels/235176658175262720/235941706116235276/753820353771471008) this might be an issue with opam but I'm creating this PR anyways since this should help newbies like me not get stuck on the first few steps :)
> Update contributor docs to install dependencies when creating switch

- ocaml-lsp-server/docs/ocamllsp/switchImplIntf-spec.md
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/switch_impl_intf.ml
- ocaml-lsp-server/src/switch_impl_intf.mli
- ocaml-lsp-server/test/e2e/__tests__/ocamllsp-switchImplIntf.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-completion.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-hover.test.ts
> implement handling 'didSwitchImplIntf' - switching between impl and intf files

- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/document.mli
- ocaml-lsp-server/src/switch_impl_intf.ml
- ocaml-lsp-server/test/e2e/__tests__/ocamllsp-switchImplIntf.ts
Fixes https://github.com/ocamllabs/vscode-ocaml-platform/issues/382:
one couldn't switch from a new file that's not saved on disk
(in vscode it's a file with URI scheme 'untitled')
The previous switching logic depended on document store, which only
knows files that were opened with a 'textDocument/didOpen'
notification. VS Code doesn't send such notifications for unsaved files,
hence the bug. Now switching handled file URIs directly without
dependence on document store, which works for any 'switchImplIntf'
request with a valid URI.
Note: handling of URIs is brittle as is the current URI module. I would strongly be in favor of adding a vendored dep `ocaml-uri`.
TODO:
> fix bug in 'switchImplIntf':

- CHANGES.md
- lsp.opam.template
- unvendor.ml
> delete vendor directory when installing lsp

- .gitmodules
- lsp.opam
- lsp.opam.template
- ocaml-lsp-server/dune
- unvendor.ml
Follow-up to #260 
For now, there are two main changes:
- commit the opam file generated from the template
- add the unix dependency for the `unvendor.ml` script
The installation of a pinned version now fails at `dune subst`, with the error:
```
Error: vendor/cmdliner: No such file or directory
```
However I don't know enough about dune to know how to fix that, ^^
> Vendor directory fixes

- dune-project
- lsp.opam
In anticipation to the activation of the new Merlin "external configuration reading", we should have a way to install `dot-merlin-reader` with `ocaml-lsp-server`.
It seems like the most reasonable way to do that is to add a package dependency.
The may advantage of this option is it's simplicity.
However it also has drawbacks:
- It is one more dependency, and the binary  `dot-merlin-reader` could be built with the already vendored sources of Merlin
- In theory the version `dot-merlin-reader` should always be in sync with the vendored version of Merlin (In practice I believe that  `dot-merlin-reader` should be fairly stable and protocol changes not frequent at all).
Other possibilities:
- Build the executable from the vendored sources. We may need to rename ocaml-lsp's `dot-merlin-reader` …
> Add dependency to `dot-merlin-reader`

- CHANGES.md
- ocaml-lsp-server/src/ocaml_lsp_server.ml
When one opens a source file of a library they use (with go-to-definition, for example), merlin reports errors in that file. When the file is closed, the errors remain in the problems pane (see the screenshot). This PR clears the reported errors when such a non-project source is closed. I define non-project source file as a file with URI that contains ".opam", "_opam", or "_esy".
> Clear diagnostics for non-project files

- dune-project
- jsonrpc.opam
- lsp.opam
- ocaml-lsp-server.opam
Right now every packages defined in this repository fails on OCaml 4.12 with the following error message:
```
File "_build/.dune/default/ocaml-lsp-server/vendor/merlin/src/ocaml/utils/dune", line 2, characters 13-25:
2 | (copy_files# 412/*.ml{,i})
^^^^^^^^^^^^
Error: Cannot find directory:
ocaml-lsp-server/vendor/merlin/src/ocaml/utils/412
```
It is safe to assume that since they're using merlin and that it is always only compatible with a limited set of the OCaml compiler, them too are also always compatible with a limited set of the compiler and thus should be restricted as such in their package description.
> Define ocaml-lsp to be only compatible with a limited set of the OCaml compiler

- jsonrpc-fiber/test/jsonrpc_fiber_tests.ml
Show that we currently cannot make requests while serving them.
~~This seems to segfault OCaml. I will look at this later.~~
Nvm, I made a silly mistake that created an infinite loop.
> test for concurrent requests

- fiber-test/dune
- fiber-unix/src/dune
- fiber-unix/test/dune
- jsonrpc-fiber/src/dune
- jsonrpc-fiber/test/dune
- jsonrpc/src/dune
- lsp-fiber/src/dune
- lsp-fiber/test/dune
- lsp/bin/dune
- lsp/src/dune
- ocaml-lsp-server/src/dune
To make it easier to compare to each dune file, I ordered all the libraries in alphabetical order, but that breaks the diff for this commit. For other things I did, I just added the `Result` library and `future_syntax` preprocess as needed. If you don't like it, I will undo the changes around the alphabetical sort.
> Fix the dune files to fix compilation errors in 4.06.x

- dune-project
- lsp.opam
- ocaml-lsp-server.opam
- ocaml-lsp-server/src/document.ml
This PR will enable the use of the new Merlin configuration system.
Its merging should be accompanied by an update of the vendored `merlin` that removes the commit [@rgrinberg/merlin#3746f6b](https://github.com/rgrinberg/merlin/commit/3746f6bdf4f7be99f71f2d42a127b3d64b8127d0) that reverts external readers-related changes.
Once merged, we will be able to merge the Dune PR that removes the promotion of `.merlin` files: [dune#3554](https://github.com/ocaml/dune/pull/3554)
(without the right vendored merlin it is expected that the CI will fail)
> External config readers

- jsonrpc-fiber/src/jsonrpc_fiber.ml
- jsonrpc-fiber/src/jsonrpc_fiber.mli
- jsonrpc-fiber/test/jsonrpc_fiber_tests.ml
- lsp-fiber/src/rpc.ml
Change the return type for `on_request` to allow concurrent handling.
> Serve requests concurrently

- dune-project
- ocaml-lsp-server.opam
The runtime component is vendored in merlin
> Remove menhir dependency

- ocaml-lsp-server/docs/ocamllsp/inferIntf-spec.md
- ocaml-lsp-server/src/code_actions/action_inferred_intf.ml
- ocaml-lsp-server/src/custom_requests/req_infer_intf.ml
- ocaml-lsp-server/src/custom_requests/req_infer_intf.mli
- ocaml-lsp-server/src/inference.ml
- ocaml-lsp-server/src/inference.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/ocamllsp-inferIntf.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-codeAction.test.ts
I've been experimenting with `workspace/applyEdit`.
I tried two options:
- Sending the request when receiving a `didOpen` for an interface that does not yet exist. Unfortunately, it does not work because VSCode does not send `didOpen` notifications for file previews. And if we save the file, then there's no way to know if the file is new or if it already exists, in which case we should not try to initialize it.
- Sending a notification when switching from an implementation to an interface that does not exist. Unfortunately, the `applyEdit` request does not seem to be processed by VSCode. Moreover, the implementation file might not be in the store, so we would need to open it manually in this case, which seem hacky.
After experimenting with it, I still think a custom request is our best …
> Add ocamllsp/inferIntf as a custom request

- lsp/src/cancel_request.ml
- lsp/src/cancel_request.mli
- lsp/src/client_notification.ml
- lsp/src/client_notification.mli
- lsp/src/server_notification.ml
- lsp/src/server_notification.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
This makes it easier to use from both the client and the server.
> Promote cancellation request to protocol level

- fiber-unix/src/barrier.ml
- fiber-unix/src/barrier.mli
- fiber-unix/src/fiber_unix.ml
- fiber-unix/src/import.ml
- fiber-unix/src/mvar.ml
- fiber-unix/src/mvar.mli
- fiber-unix/src/scheduler.ml
- fiber-unix/test/barrier_tests.ml
- fiber-unix/test/scheduler_tests.ml
- lsp-fiber/test/lsp_fiber_test.ml
The previous implementation relied on Thread.delay which was not
interruptible once the awaker was already asleep and we were waiting to
write into the mvar.
Barrier is a poor man's implementation of `pthread_cond_wait`, which I tried to
avoid binding to. @mnxn could you check that this work on windows?
> Use proper barrier for timer awaker

- ocaml-lsp-server/src/compl.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-signatureHelp.ts
Depends on https://github.com/rgrinberg/merlin/pull/9
Passes the result of `Compl.prefix_of_position` to merlin so it can determine which labelled parameter is active.
Original issue pointed out in this comment: https://github.com/ocaml/ocaml-lsp/pull/324#issuecomment-737107231
Examples:
> Use completion prefix to determine active signature help parameter

- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-signatureHelp.ts
Depends on https://github.com/rgrinberg/merlin/pull/10
Uses the position information from merlin to query for the documentation of the function being applied. Like hover, it can return either plaintext or markdown-formatted documentation.
Example:
> Show function documentation for signatureHelp

- lsp-fiber/src/import.ml
- lsp-fiber/src/rpc.ml
- lsp-fiber/src/rpc.mli
- ocaml-lsp-server/src/document.ml
Now `$/cancelRequest` is used to release positions in the merlin queue
In the future, we'll need something a little more robust. Such as:
- Run cancellers inside Fiber_detached
- Allow to hook finalizers as well as cancellers
> Implement basic cancellation

- .ocamlformat
- fiber-unix/src/barrier.ml
- fiber-unix/src/barrier.mli
- fiber-unix/src/scheduler.ml
- fiber-unix/test/barrier_tests.ml
- fiber-unix/test/dune
- ocaml-lsp-server/src/compl.ml
We're not handling errors as well as we should. It should not be possible to
await/signal after close.
> Add some tests for barrier

- ocaml-lsp-server/src/custom_requests/req_infer_intf.ml
- ocaml-lsp-server/src/custom_requests/req_switch_impl_intf.ml
It seems that `vscode-languageclient.7.0.0` changed the way parameters are send to the LSP servers for custom requests and now send a list of string when sending a string. This broke out custom requests. This PR handles the new format send by VSCode client.
> Support new languageclient format

- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/inference.ml
Can anyone tell me why this doesn't work?
The problem: In my editor, when I edit an `.eliomi` file it is still treated as an `Impl` and not a `Intf` file. Does my editor have to inform ocaml-lsp about the fact that the file should be treated as an interface?
> support eliom file extensions

- README.md
... by replacing `make build` with `make all` in accordance with Makefile changes in https://github.com/ocaml/ocaml-lsp/pull/329.
> Fix source installation instructions

- README.md
The existing instructions mention the `build` and `lsp-server` targets, which do not exist anymore. This PR fixes that.
> README.md: Fix build instructions in 'Contributing to project'

- jsonrpc-fiber/test/jsonrpc_fiber_tests.ml
- jsonrpc/src/jsonrpc.ml
- jsonrpc/src/jsonrpc.mli
- lsp-fiber/test/lsp_fiber_test.ml
- lsp/src/client_notification.ml
- lsp/src/client_request.ml
- lsp/src/client_request.mli
- lsp/src/server_notification.ml
- lsp/src/server_request.ml
- lsp/src/server_request.mli
- ocaml-lsp-server/src/custom_requests/req_infer_intf.ml
- ocaml-lsp-server/src/custom_requests/req_infer_intf.mli
- ocaml-lsp-server/src/custom_requests/req_switch_impl_intf.ml
- ocaml-lsp-server/src/custom_requests/req_switch_impl_intf.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/ocamllsp-inferIntf.ts
- ocaml-lsp-server/test/e2e/__tests__/ocamllsp-switchImplIntf.ts
Only objects or arrays are allowed as parameters. We reflect this in the
new `Structured.t` type for this field.
This drops support for older versions of the client. So we can only merge this
once everyone upgrades.
> Comply to jsonrpc spec

- CHANGES.md
- ocaml-lsp-server/src/code_actions/action_annotate.ml
- ocaml-lsp-server/src/code_actions/action_annotate.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-codeAction.test.ts
New code action `annotate`, that adds a type next to the value on which the action is called. The goal is to be able to turn `let x = x + 1` into `let (x : int) = x + 1`.
I'm missing a few things before the PR is ready.
1. [x] I don't know how to get in the file what is in the original range of text
1. [x] I need to get the name of the type only and not its detail, for example in this snippet I should get `let f (x : t) = (x : t)` and not `let f (x : t) = (x : type t = Foo of int | Bar of bool)`
```
type t = Foo of int | Bar of bool
let f (x : t) = x
```
fix #396
> Add code action annotate

- lsp/bin/ocaml/ocaml.ml
- lsp/src/import.ml
- lsp/src/text_document.ml
- lsp/src/types.ml
- lsp/src/types.mli
- lsp/src/uri0.mli
- ocaml-lsp-server/src/code_actions/action_destruct.ml
- ocaml-lsp-server/src/code_actions/action_inferred_intf.ml
- ocaml-lsp-server/src/code_actions/action_type_annotate.ml
- ocaml-lsp-server/src/compl.ml
- ocaml-lsp-server/src/custom_requests/req_infer_intf.ml
- ocaml-lsp-server/src/custom_requests/req_switch_impl_intf.ml
- ocaml-lsp-server/src/document_symbol.ml
- ocaml-lsp-server/src/inference.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
Make DocumentUri equivalent to Uri0. This removes a bunch of conversions.
> Simplify URI handling

- jsonrpc-fiber/src/jsonrpc_fiber.ml
- jsonrpc-fiber/src/jsonrpc_fiber.mli
- jsonrpc-fiber/test/jsonrpc_fiber_tests.ml
When we terminate a server, we need to make sure currently pending
requests are eliminated
> Stop pending requests on disconnect

- jsonrpc-fiber/src/jsonrpc_fiber.ml
- jsonrpc-fiber/test/jsonrpc_fiber_tests.ml
A recursive call inside a fork is going to allocate a closure that will only be
collected by the GC once all the recursive calls are done. Since we are looping
over all incoming packets, that's essentially a memory leak. This PR removes the
calls to fork_and_join_unit that rely on recursion.
I was always aware of this leak, but never bothered to fix it since it's quite
tiny (1 closure per incoming packet). I was looking for ways to use it other
than a pool, but eventually gave up.
> Fix jsonrpc memory leak

- fiber-unix/src/scheduler.ml
- fiber-unix/src/scheduler.mli
- jsonrpc-fiber/src/import.ml
- jsonrpc-fiber/src/jsonrpc_fiber.ml
- jsonrpc-fiber/src/jsonrpc_fiber.mli
- lsp-fiber/src/fiber_io.ml
- lsp-fiber/src/rpc.ml
- lsp-fiber/src/rpc.mli
- lsp-fiber/test/lsp_fiber_test.ml
- ocaml-lsp-server/src/code_actions/action_destruct.ml
- ocaml-lsp-server/src/code_actions/action_destruct.mli
- ocaml-lsp-server/src/code_actions/action_inferred_intf.ml
- ocaml-lsp-server/src/code_actions/action_inferred_intf.mli
- ocaml-lsp-server/src/code_actions/action_type_annotate.ml
- ocaml-lsp-server/src/code_actions/action_type_annotate.mli
- ocaml-lsp-server/src/compl.ml
- ocaml-lsp-server/src/compl.mli
- ocaml-lsp-server/src/custom_requests/req_infer_intf.ml
- ocaml-lsp-server/src/custom_requests/req_infer_intf.mli
- ocaml-lsp-server/src/custom_requests/req_switch_impl_intf.ml
- ocaml-lsp-server/src/custom_requests/req_switch_impl_intf.mli
- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/document.mli
- ocaml-lsp-server/src/document_store.ml
- ocaml-lsp-server/src/document_store.mli
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/inference.ml
- ocaml-lsp-server/src/inference.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
First of all I removed all the result types in LSP. The code much cleaner
without all this extra noise, and I apologize to the other contributors for
cargo culting this silly style.
I fixed how `Jsonrpc.Response.Error.E` are handled. They are now passed as responses
instead of being wrapped as internal errors.
Finally, exceptions are now reported to clients as soon as possible. This has
the advantage that the client will see errors sooner, but the disadvantage that
we aren't reporting all errors. I think it's a good trade off.
> Improve error handling

- fiber-unix/src/scheduler.ml
- fiber-unix/src/scheduler.mli
- fiber-unix/test/scheduler_tests.ml
- ocaml-lsp-server/src/fmt.ml
- ocaml-lsp-server/src/fmt.mli
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/state.ml
- ocaml-lsp-server/src/state.mli
This allows us to run ocamlformat asynchronously. This is not very useful right
now, but will be once we run ocamlformat in server mode and use dune rpc.
> Support async waiting for process

- Makefile
- lsp/src/dune
- lsp/src/import.ml
- lsp/src/uri0.ml
- lsp/src/uri0.mli
- lsp/src/uri_lexer.mli
- lsp/src/uri_lexer.mll
- lsp/test/dune
- lsp/test/uri_tests.ml
- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/document_store.ml
> Fix extracting path from URI

- CHANGES.md
- ocaml-lsp-server/src/document.ml
This matches merlin's default behavior and prevents stack overflows in some
situations.
> Revert verbosity back to 0

- ocaml-lsp-server/src/fmt.ml
- ocaml-lsp-server/src/fmt.mli
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-formatting.test.ts
Uses a simple diff algorithm to return a list of `TextEdit`s  for the delta from `ocamlformat`/`refmt`, rather than just returning a single `TextEdit` that replaces the whole file.
Why
===
My particular use case (from emacs with evil-mode):
- In my case I use emacs, and have it configured to format-on-save
- I noticed I had slow performance on some edits using `evil-mode`(/ spacemacs), which became almost unusable on large files, which I'd assumed was due to `tuareg`/`font-lock`. In particular, `O`  and `dd` would take a long time O(1s) to complete, which is pretty jarring.
- On closer investigation, I noticed performance was initially fine on these large files, but poor editing performance started after the first format of the buffer.
- The reason for this was `evil-mode` calling the …
> textDocument/formatting: return diff of changes

- ocaml-lsp-server/test/e2e/__tests__/textDocument-hover.test.ts
Does what's said on the tin :p 
See #344 for issue description and when the bug occurs.
> reproduce wrong-doc-on-hover bug from #344

- fiber-unix/src/scheduler.ml
- fiber-unix/src/scheduler.mli
- fiber-unix/test/scheduler_tests.ml
- lsp-fiber/src/fiber_io.ml
- lsp-fiber/src/fiber_io.mli
- lsp-fiber/test/lsp_fiber_test.ml
- ocaml-lsp-server/src/dune.ml
- ocaml-lsp-server/src/dune.mli
- ocaml-lsp-server/src/fmt.ml
- ocaml-lsp-server/src/fmt.mli
- ocaml-lsp-server/src/inference.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/state.ml
- ocaml-lsp-server/src/state.mli
Anything that needs the scheduler must now return Fiber.t
This brings us our code closer to dune's scheduler which we'll eventually adopt.
> Remove explicit schedulers

- CHANGES.md
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-diagnostics.ts
The utility is small because OCaml doesn't use sub-messages as much as it
should.
> Support related errors in diagnostics

- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/range.ml
- ocaml-lsp-server/src/range.mli
- ocaml-lsp-server/test/e2e/__tests__/textDocument-diagnostics.ts
https://github.com/ocamllabs/vscode-ocaml-platform/pull/640 uses this PR to add support for commands to jump to previous/next typed hole. 
This is the first PR in a series to add support for merlin `Construct` command in ocaml-lsp.
> Show typed holes as errors

- ocaml-lsp-server/docs/ocamllsp/typedHoles-spec.md
- ocaml-lsp-server/src/custom_requests/req_typed_holes.ml
- ocaml-lsp-server/src/custom_requests/req_typed_holes.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/ocamllsp-typedHoles.ts
Adds a custom request `ocamllsp/typedHoles`, which is used by https://github.com/ocamllabs/vscode-ocaml-platform/pull/643
> Add custom request `ocamllsp/typedHoles`

- CHANGES.md
- ocaml-lsp-server/src/code_actions/action_destruct.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-codeAction.test.ts
- Is based on #467 and https://github.com/ocamllabs/vscode-ocaml-platform/pull/643
- I am not sure whether embedding in a code action a command, which is not available in an editor results in user-visible warning or error; if that's the case, I can add the command only for vscode client
The gif below shows how jumps to first holes work along with jumping to prev/next holes.
https://user-images.githubusercontent.com/16353531/123289585-05591900-d52a-11eb-97db-f5d94b1441b9.mov
> Jump to the first hole on destruct

- .github/workflows/build-and-test.yml
- .ocamlformat
- CHANGES.md
- Makefile
- dune-project
- lsp.opam
- lsp/src/types.ml
- nix/default.nix
- nix/opam-selection.nix
- ocaml-lsp-server.opam
- ocaml-lsp-server/src/dune
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/ocamlformat_rpc.ml
- ocaml-lsp-server/src/ocamlformat_rpc.mli
- ocaml-lsp-server/src/state.ml
- ocaml-lsp-server/src/state.mli
- shell.nix
This PR add support for formatting of types in popups. Types provided by Merlin are not always nicely formatted and module signatures often wrap because it exceeds the maximum number of columns of a VSCode popup (64 characters on my setup). The idea is to use OCamlformat to format these types, but starting a new process would be to heavy for that usage.
In a joint effort with the OCamlformat team this PR acheive type formatting by spawning an "OCamlformat RPC server" and then communicating with it using a simple protocol. The protocol is vendored for now (in the file `ocamlformat_rpc_lib.ml` but will be made available as a separate and common package.
In case of failure to start the server, negotiate a version or receive a response we log some information and fallback to the non-formatted …
> OCamlformat RPC

- CHANGES.md
- ocaml-lsp-server/src/compl.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-completion.test.ts
When reconstructing prefix, we were ignoring backtick, which resulted in wrong completion entries, see the first commit.
I modified prefix building function to 
- not ignore a backtick 
- make sure that if the prefix that we were building already included a dot, e.g., the prefix so far is `Fiber.return`, we ignore the backtick that, say, comes before that prefix ie `Fiber.return. (I understand that the user shouldn't put the backtick there in the first place, but let's provide the best completions when we can)
I used some mutations along with `String.rfindi` instead of hand-writing the loop because I though it's still easier to reason about that a hand-written loop.
> Fix completion for polymorphic variants

- CHANGES.md
- ocaml-lsp-server/src/dune
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-diagnostics.ts
- ocaml-lsp-server/vendor/dune
Dune already has a library to parse compiler errors into a more structured form for better error reporting in watch mode. So we might as well use it to improve the errors we get from merlin.
> Improve display of merlin errors

- CHANGES.md
- ocaml-lsp-server/src/code_actions/action_refactor_open.ml
- ocaml-lsp-server/src/code_actions/action_refactor_open.mli
- ocaml-lsp-server/src/code_actions/code_action.ml
- ocaml-lsp-server/src/code_actions/code_action.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-codeAction.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-hover.test.ts
Reservations I have:
Blockers: 
```ocaml
open Unix (* both qualify and unqualify code actions will be shown *)
let u = () 
```
To-do
> add support for refactor-open (qualify and unqualify) code action

- CHANGES.md
- ocaml-lsp-server/docs/ocamllsp/wrappingAstNode-spec.md
- ocaml-lsp-server/src/custom_requests/custom_request.ml
- ocaml-lsp-server/src/custom_requests/custom_request.mli
- ocaml-lsp-server/src/custom_requests/req_wrapping_ast_node.ml
- ocaml-lsp-server/src/custom_requests/req_wrapping_ast_node.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/ocamllsp-wrappingAstNode.test.ts
This PR adds support for "Evaluate expression under cursor".
This PR will soon have a counter-part in vscode-ocaml-platform repo. From that PR's changelog:
Let's see some examples (`<n>` is cursor position for example number `n`)
```ocaml
let k = <1> 1
<2>
module M = struct<3>
let a =
let <4> b = 1 in
b + 1
<5>
let u = ()
end
```
| Your cursor | Evaluated expression        | Rationale                                                                                        |
| ----------- | --------------------------- | ------------------------------------------------------------------------------------------------ |
| <1>         | `let k = 1`                 | Toplevel expression under cursor                                                                 |
| <2>         | whole code block …
> Add support for a custom request to get AST node enclosing the cursor (for REPL support)

- ocaml-lsp-server/src/range.ml
The first line in LSP is zero-based. Fixing the bug﻿
> Fix: first line is 0-based

- ocaml-lsp-server/test/e2e/__tests__/textDocument-declaration.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-definition.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-typeDefinition.test.ts
- ocaml-lsp-server/test/e2e/jest.config.js
- ocaml-lsp-server/test/e2e/jest.setup.ts
- ocaml-lsp-server/test/e2e/src/LanguageServer.ts
This PR moves the function that extends jest matchers with the `toEqualUri` to its own file, and add it to the [setupFilesAfterEnv](https://jestjs.io/docs/26.x/configuration#setupfilesafterenv-array) config. By doing so, it will be available in every test file by default.
> move jest extend matchers in jest.setup.ts

- CHANGES.md
- ocaml-lsp-server/src/dune.ml
- ocaml-lsp-server/src/dune.mli
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/state.ml
- ocaml-lsp-server/src/state.mli
- ocaml-lsp-server/src/workspaces.ml
- ocaml-lsp-server/src/workspaces.mli
The server will now maintain the set of open workspace folders and use
this set for querying symbols.
Support for dune is a bit more complicated, but the idea is going to be manage a dune connection per workspace folder.
> Handle workspace change notifications

- dune
- lsp-fiber/src/dune
- lsp/src/dune
- ocaml-lsp-server/src/dune
- ocaml-lsp-server/src/dune.ml
- ocaml-lsp-server/src/dune.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
This will allow vscode to display diffs. I'm not sure if the client should provide a capability that tells us if it can do anything with this information. Of course it can always just ignore this data.
> Add dune promotion information to diagnostics

- CHANGES.md
- ocaml-lsp-server/src/compl.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-completion.test.ts
`prefix_of_position` is getting complicated; I hope we're not breaking anything with this fix
> Fix completion for symbols passed as named arg

- CHANGES.md
- ocaml-lsp-server/src/code_actions/action_mark_remove_unused.ml
- ocaml-lsp-server/src/code_actions/action_mark_remove_unused.mli
- ocaml-lsp-server/src/code_actions/diagnostic_util.ml
- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/document.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-codeAction.test.ts
Adds code actions for marking unused code (i.e. by prepending '_' to variable names) and for removing unused code. Currently it can remove unused types, modules, opens, constructors, and variables.
> Code actions for marking & removing unused code

- ocaml-lsp-server/test/e2e/__tests__/ocamllsp-switchImplIntf.ts
The upgrade to node v16 introduced in #522 broke one of the e2e tests. This PR should fix it.
> fix e2e tests node v16

- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/document.mli
In preparation for formatting dune files.
The change itself isn't very clean - we'd prefer a more a type safe approach. For now, we'd like to get the feature out and refactor later.
> refactor: add dune documents

- fiber-test/fiber_test.ml
- fiber-unix/src/scheduler.ml
- fiber-unix/test/scheduler_tests.ml
- jsonrpc-fiber/src/jsonrpc_fiber.ml
- jsonrpc-fiber/test/jsonrpc_fiber_tests.ml
- lsp-fiber/src/fiber_io.ml
- lsp-fiber/src/rpc.ml
- lsp-fiber/test/lsp_fiber_test.ml
- ocaml-lsp-server/src/code_actions/action_add_rec.ml
- ocaml-lsp-server/src/code_actions/action_construct.ml
- ocaml-lsp-server/src/code_actions/action_destruct.ml
- ocaml-lsp-server/src/code_actions/action_inferred_intf.ml
- ocaml-lsp-server/src/code_actions/action_refactor_open.ml
- ocaml-lsp-server/src/code_actions/action_type_annotate.ml
- ocaml-lsp-server/src/custom_requests/req_infer_intf.ml
- ocaml-lsp-server/src/custom_requests/req_typed_holes.ml
- ocaml-lsp-server/src/custom_requests/req_wrapping_ast_node.ml
- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/document_store.ml
- ocaml-lsp-server/src/document_symbol.ml
- ocaml-lsp-server/src/dune.ml
- ocaml-lsp-server/src/fmt.ml
- ocaml-lsp-server/src/inference.ml
- ocaml-lsp-server/src/ocamlformat_rpc.ml
- ocaml-lsp-server/src/progress.ml
It added too much noise for little benefit. After we get rid of result, bind is basically the same thing everywhere.
> refactor: no more local open of fiber

- ocaml-lsp-server/test/e2e/__tests__/textDocument-declaration.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-definition.test.ts
- ocaml-lsp-server/test/e2e/src/LanguageServer.ts
Splitting out the commit from #545 (will rebase that PR) - issue with the `toEqualUri` helper not asserting correctly.
> fix: jest toEqualUri helper and expected results

- ocaml-lsp-server/src/dune.ml
- ocaml-lsp-server/src/dune.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
Run the dune formatter through lsp. @ulugbekna @mnxn we need to co-ordinate disabling formatting on vscode for these files.
> feature: format dune files

- Makefile
Without the quotes in bash a file `=v0.14.0` is created with the output of the command and the installation can get stuck because the Y/N prompt isn't visible.
> Avoid unexpected shell redirection to file in make install-test-deps

- nix/default.nix
`builtins.filterSource` checks files and directories *deeply*, so all the source files deeper than project root are abandoned at nix build.
The PR suggests to use `gitIgnoreSourcePure` to ignore files unneeded at build by using `.gitignore`.
> (nix) Replace hand-written source filtering to nix-gitignore

- ocaml-lsp-server/src/folding_range.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-foldingRange.test.ts
Currently, we can only fold the entire class. This PR adds basic support for folding what's defined in the class itself.
First commit only moves some tests
https://user-images.githubusercontent.com/5595092/148347407-621a8398-8271-41db-bfc9-4be115f73a75.mov
Let me know if you can think of anything else, definitely not used to using classes myself.
> add basic support for classes folding

- ocaml-lsp-server/src/folding_range.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-foldingRange.test.ts
`Pexp_sequence` nodes were not traversed, leading to the issue highlighted in the video below.
* First commit adds a test
* Second commit fixes the issue
https://user-images.githubusercontent.com/5595092/148502160-09682340-8ea3-47e6-9ab6-a73da7208d21.mov
> [Folding ranges]: traverse Pexp_sequence nodes

- Makefile
- nix/default.nix
- nix/opam-selection.nix
Considering below logs, Menhir 20211230 may contain a bug about type inference:
https://github.com/Nymphium/ocaml-lsp/runs/4754176481?check_suite_focus=true#step:10:31
This PR adds constraint to Menhir in test dependencies.
> Add constraint to menhir as test deps

- ocaml-lsp-server/src/folding_range.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-foldingRange.test.ts
Support folding with explicit return type annotation. Fix the following case:
https://user-images.githubusercontent.com/5595092/150073804-88daba85-8fd9-4c80-829b-7d99d2afb103.mov
> [Folding ranges]: support return type annotation

- ocaml-lsp-server/src/folding_range.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-foldingRange.test.ts
For now, it only traverses the `Pexp_ifthenelse` so what's inside can be folded. 
https://user-images.githubusercontent.com/5595092/150080689-109f670e-333a-4804-a3ae-986487edc221.mov
Initially, I wanted to add support for folding the entire `if` and `else` but I'm not sure how to do it because the locations are the ones from the expressions themselves (`if_expr`, `then_expr` and `else_expr`) and don't take into account the location of the `if`/`else` keywords
> [Folding ranges]: support if/else

- ocaml-lsp-server/src/folding_range.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-foldingRange.test.ts
It only traverses the `Pexp_try` for now. Not sure how we could support folding the `try` and `with` separately due to the way locations are reported (same as with the if/else).
We could add support for folding the entire `try/with` expression though. Do we want to support that?
> [Folding ranges]: support try/with

- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/document.mli
- ocaml-lsp-server/src/hover_req.ml
- ocaml-lsp-server/src/hover_req.mli
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/state.ml
- ocaml-lsp-server/src/state.mli
Mostly moves code around to help with https://github.com/ocaml/ocaml-lsp/pull/561#issuecomment-1008457123:
> Anyway, in the process of adding a new command I had to duplicate quite a lot of code from ocaml_lsp_server.ml to req_hover_extended.ml. Because the later is called from the former. So all the utils can't be called from the custom commands. I wonder where I should move that code to avoid duplication.
> [refactor] extract hover request handling in separate file

- CHANGES.md
- ocaml-lsp-server/src/dune
- ocaml-lsp-server/src/ocaml_lsp_server.ml
> fix: improve error messages when merlin is absent

- CHANGES.md
- lsp/src/cancel_request.ml
- lsp/src/import.ml
- fix: better missing json-field error formatting
- fix: $/cancelRequest params were incorrectly (de)serialized
Noticed this problem luckily thanks to learning how to use logging yesterday :D
> Fix cancel request param (de)serialization

- ocaml-lsp-server/src/ocamlformat.ml
do not pass non-blocking fd's to ocamlformat
> fix(ocamlformat): pass fd's correctly

- jsonrpc-fiber/src/jsonrpc_fiber.ml
- lsp-fiber/src/fiber_io.ml
- lsp-fiber/src/rpc.ml
- ocaml-lsp-server/src/compl.ml
- ocaml-lsp-server/src/custom_requests/req_infer_intf.ml
- ocaml-lsp-server/src/custom_requests/req_switch_impl_intf.ml
- ocaml-lsp-server/src/custom_requests/req_switch_impl_intf.mli
- ocaml-lsp-server/src/custom_requests/req_typed_holes.ml
- ocaml-lsp-server/src/custom_requests/req_wrapping_ast_node.ml
- ocaml-lsp-server/src/diagnostics.ml
- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/document_store.ml
- ocaml-lsp-server/src/folding_range.ml
- ocaml-lsp-server/src/hover_req.ml
- ocaml-lsp-server/src/inference.ml
- ocaml-lsp-server/src/merlin_config.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/ocamlformat.ml
- ocaml-lsp-server/src/progress.ml
If a function returns Fiber.t, it should shift all side effects into the fiber.
I've been sloppy about this before, but from now let's keep it strict. cc @ulugbekna
> refactor: move side-effects into fiber

- README.md
The current description of the 'Contributing to project' section in README.md uses `--with-test` option to install dependencies before `make all`, but in my environment, it fails due to library-not-found errors. According to https://github.com/ocaml/ocaml-lsp/commit/62872323c1b14da42a0d451fad173d4af25c379f, the dependencies should be installed by `make install-test-deps` before `make all`, and it succeeded in my environment. Also, the built executable is located at `_build/default/ocaml-lsp-server/bin/main.exe` now. This patch fixes these problems.
> Fix 'Contributing to project' section in README.md

- ocaml-lsp-server/vendor/dune
xdg doesn't need to be vendored anymore
> chore: remove vendoring dune rules for xdg

- dune-project
- lsp-fiber/src/dune
- ocaml-lsp-server.opam
we don't need it because merlin dropped it
> chore: remove result dependency

- lsp/src/uri0.ml
@rgrinberg as discussed on Slack. I don't see any special behaviour for the path (but only `fsPath` and `Uri.file`) on windows in the `vscode-uri` test suite: https://github.com/microsoft/vscode-uri/blob/main/src/test/uri.test.ts#L156
So I assume that's fine to add a leading `/` on windows too. I can't test it though since I don't have a windows machine.
> add leading slash to Uri.to_path on windows

- dune-project
- lsp.opam
- lsp/src/dune
- lsp/src/import.ml
- lsp/src/snippet.ml
do not use Code_error in the lsp library
> chore: get rid of stdune in lsp

- ocaml-lsp-server/src/folding_range.ml
example:
```ocaml
include struct
let u = ()
end
```
> feat(folding range): support `include`

- ocaml-lsp-server/test/e2e/__tests__/TextDocument.test.ts
- ocaml-lsp-server/test/e2e/__tests__/completionItem-resolve.test.ts
- ocaml-lsp-server/test/e2e/__tests__/ocamllsp-inferIntf.ts
- ocaml-lsp-server/test/e2e/__tests__/ocamllsp-switchImplIntf.ts
- ocaml-lsp-server/test/e2e/__tests__/ocamllsp-typedHoles.ts
- ocaml-lsp-server/test/e2e/__tests__/ocamllsp-wrappingAstNode.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-codeAction.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-codeLens.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-completion.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-declaration.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-definition.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-diagnostics.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-documentHighlight.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-documentSymbol.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-foldingRange.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-formatting.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-references.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-rename.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-selectionRange.test.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-signatureHelp.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-typeDefinition.test.ts
- ocaml-lsp-server/test/e2e/__tests__/workspace-symbol.test.ts
- ocaml-lsp-server/test/e2e/jest.config.js
- ocaml-lsp-server/test/e2e/src/LanguageServer.ts
- ocaml-lsp-server/test/e2e/src/utils.ts
- ocaml-lsp-server/test/e2e/tsconfig.json
* Update TS to the latest version
* Turn on TS strict flag
* Avoid using string for request type (use `vscode-languageserver-protocol` instead)
* Remove unnecessary `await`
> test: refactor e2e tests

- ocaml-lsp-server/src/code_actions.ml
- ocaml-lsp-server/src/code_actions.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
This PR is nothing more than just moving code around. 
Why? 
1. I am experimenting with how code actions' merlin work could be run at once rather than in different fibers (related [comment](https://github.com/ocaml/ocaml-lsp/blob/bd0c6402bbd2373333e833ea7c7b4f08112877fa/ocaml-lsp-server/src/ocaml_lsp_server.ml#L407-L408)) [*]
2. Some of the code is code action-specific, so having a separate module offers good separation of concern 
3. `ocaml_lsp_server.ml` is already big, let's lighten it when we can
[*] There are two things I'd like to mention about refactoring code actions: 
1. Code actions can be split by two properties: 
1) Whether they are offered only in presence of certain diagnostics. For example, quick fix code actions that are aimed at changing code only when a certain …
> refactor(olsp): extract code actions computation into a separate file

- dune-project
- nix/opam-selection.nix
- ocaml-lsp-server.opam
cc @rgrinberg omd 1.3.2 now builds with dune.
There's a dependency constraint on Windows:
```
C:\Windows\system32\cmd.exe /D /S /C "D:\cygwin\wrapperbin\opam.cmd depext jsonrpc lsp ocaml-lsp-server"
[ERROR] No solution for jsonrpc & lsp & ocaml-lsp-server: The following dependencies couldn't be met:
- ocaml-lsp-server -> omd (>= 1.3.2 & < 2.0.0~alpha1) -> ocaml < 4.06.0
base of this switch (use `--unlock-base' to force)
Your request can't be satisfied:
- No available version of omd satisfies the constraints
```
Any idea what's wrong?
> chore(ocamllsp): update omd

- ocaml-lsp-server/src/ocaml_lsp_server.ml
Sub processes such as ocamlformat-rpc, refmt (heaven forbid) might crash
on us. We should not terminate the server because of that.
ps-id: ab654253-9786-4ea6-96d2-260389712b47
> fix(ocamllsp): ignore sigpipe

- CHANGES.md
- ocaml-lsp-server/src/ocaml_lsp_server.ml
As soon as I open a .mll file (with filetype set to ocamllex in NeoVim) the LSP
server sends a continuous stream "Document.dune" exceptions.
I currently have to turn off Lsp (using :LspStop) to be able to keep
editing.
Instead of raising an exception just return an empty result for
filetypes where signatureHelp is not implemented yet.
It'd probably be better to not advertise the capability, but not sure if
that is doable by filetype...
> fix(ocamllex): do not raise exceptions on signatureHelp

- ocaml-lsp-server/src/code_actions/action_mark_remove_unused.ml
- ocaml-lsp-server/src/code_actions/diagnostic_util.ml
- ocaml-lsp-server/src/diagnostics.ml
- ocaml-lsp-server/src/diagnostics.mli
- ocaml-lsp-server/src/dune.ml
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
> feature(olsp): warning for unused symbols are marked using `DiagnosticTag.Unnecessary`

- CHANGES.md
- ocaml-lsp-server/src/code_actions/diagnostic_util.ml
- ocaml-lsp-server/src/diagnostics.ml
> Tag deprecated warnings

- flake.nix
use "*" instead of null as recommended by opam-nix
ps-id: fc183cbc-f3ad-4f64-a011-270b186de3db
> chore(nix): fix warnings

- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/signature_help.ml
Now that Merlin exposes its internals `Signature_help` can be implemented without upstream modification.
> Use `merlin-lib` to implement Signature_help

- CHANGES.md
- ocaml-lsp-server/src/code_actions.ml
- ocaml-lsp-server/src/code_actions/action_inline.ml
- ocaml-lsp-server/src/code_actions/action_inline.mli
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e-new/action_inline.ml
- ocaml-lsp-server/test/e2e-new/code_actions.ml
- ocaml-lsp-server/test/e2e-new/start_stop.ml
- ocaml-lsp-server/test/e2e-new/test.ml
This PR adds an inlining code action for non-top-level let bindings. For example,
```ocaml
let test y =
let x = y + 1 in
^
x + 2
```
turns into 
```ocaml
let test y =
let x = y + 1 in
(y + 1) + 2
```
after inlining.
Caveats:
- The inlining context can shadow bindings in the body, which changes the meaning of the inlined code. I.e., this transformation isn't sound. We should at least be able to use Merlin to detect this and block the action, but I'm not sure how.
- Right now I'm using `Untypeast` followed by `Pprintast` to turn the body of the let into a string. This means that comments are stripped and the inlined code contains expanded PPXes. This should be fixable by using the source code the body, but it requires a bit more care when inlining functions.
- The original definition is not …
> Add code action for inlining

- CHANGES.md
- ocaml-lsp-server/src/merlin_config.ml
In Merlin we decided to ignore unknown configuration tags when the provider is Dune.
This allows for easier forward compatibility if the protocol gets extended (with, for example, a new tag).
Since this part of the configuration management is re-implemented in ocaml-lsp-server this PR re-apply that Merlin change.
> Ignore unknown config tags

- flake.nix
it's been moved into ocamlformat
ps-id: 9b44bd8a-0de4-4019-864e-75553ff1d3f9
> chore: remove ocamlformat-rpc

- ocaml-lsp-server/src/ocaml_lsp_server.ml
fix(go-to-def): send a response with an error for failing go-to-def/go-to-decl/go-to-type-def
rather than a notification afterwards with the error
also, should `definition_query`'s body be wrapped in `Fiber.of_thunk` ?
> fix(go-to-def): report error in response

- CHANGES.md
- ocaml-lsp-server/src/diagnostics.ml
- ocaml-lsp-server/src/diagnostics.mli
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/state.ml
- ocaml-lsp-server/src/state.mli
- ocaml-lsp-server/test/e2e/__tests__/textDocument-diagnostics.ts
Make sure the client supports them via the client capabilities
ps-id: 7969575f-a6aa-4430-a7c0-5f2632484e63
> fix: offer related information only when supported

- ocaml-lsp-server/src/semantic_highlighting.ml
- refactor(semantic-hl):  remove redundant code
- update comments; add signature to `Parsetree_fold`
> document semantic highlighting module

- CHANGES.md
- ocaml-lsp-server/src/dune.ml
See #929. 
With this PR, we do not start the inifinite loop that is watching the "dune/rpc" file on windows. 
This loop exists to communicate with dune in watch mode... which is not yet supported on windows (although it should be supported "soonish" when https://github.com/ocaml/dune/pull/6087 will be merged). So, in practice, on windows, this loop is basically an infinite thread doing nothing but failing calls to `Unix.stat`. That is exactly what's needed to trigger ocaml/ocaml#11737.
Note: even with this PR, the ocaml bug could still lead to a segfault each time we do a Unix.stat on non-existing file. But 
with this PR, it should be harder to trigger. 
This PR should be reverted as soon as all supported compilers have ocaml/ocaml#11737 (> 4.14.0 ?) which, hopefully, should happen before …
> Mitigate ocaml/ocaml#11737 (windows-only)

- CHANGES.md
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- fix(ofmt-rpc): disable ofmt-rpc for formatting files because it doesn't respect missing .ocamlformat and formats projects using default config
- refactor(formatter): cleaner error handling
> disable ofmt rpc for files

- ocaml-lsp-server/src/configuration.ml
- ocaml-lsp-server/src/env_vars.ml
- ocaml-lsp-server/src/hover_req.ml
- ocaml-lsp-server/src/import.ml
The commit comment explains why. 
Ideally, we would write a config file for env vars, from which we could generate both `Env_vars` module and documentation for README, but that seems unnecessary right now. 
I can also shadow `Sys.getenv` and `Sys.getenv_opt` with empty functions, if we want to ensure people use `Env_vars` rather than those by `Sys` module.
> unite all olsp env var handling

- CHANGES.md
- ocaml-lsp-server/src/code_actions/action_inline.ml
- ocaml-lsp-server/src/code_actions/action_type_annotate.ml
- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/folding_range.ml
- ocaml-lsp-server/src/merlin_config.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/semantic_highlighting.ml
- ocaml-lsp-server/src/signature_help.ml
- ocaml-lsp-server/test/e2e/__tests__/ocamllsp-hoverExtended.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-hover.test.ts
ps-id: ea784131-dd41-4181-add7-fd3e5e304b00
> chore: update merlin

- CHANGES.md
I don't know whether we want a normal release for ocaml 4 or not, hence "unreleased"
sorry for the noise with all these PRs
> chore(changes): remove incorrect version

- CHANGES.md
- README.md
Cleans up CHANGES and updates version number
@rgrinberg we have dune polling disabled for ocaml 4.14. Do I understand correctly that we don't need it disabled for ocaml 5 since the upstream issue is fixed?
also, perhaps, it makes sense to have release version in CHANGES set to 1.15.0-4.14 on master (vs. just 1.15.0) and 1.15.0-5.0 on 500?
> prepare 1.15.0

- ocaml-lsp-server/src/definition_query.ml
- ocaml-lsp-server/src/definition_query.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
Move goto-definition to own module
> refactor(ocamllsp): move definition to own module

- ocaml-lsp-server/src/dune.ml
The most common cause of this issue is not running `dune` in watch mode;
therefore, there is no registry to be polled. The current error message
doesn't make it clear that this behavior is expected.
We probably don't want to make polling conditional on existence of the
socket, since the current implementation allows users to run `dune
--watch` without restarting the lsp server.
Expanding the error message makes it clear that this behavior is
intentional, and suggests the "fix".
Signed-off-by: Alexander Skvortsov <sasha.skvortsov109@gmail.com>
> feat: improve error message when can't poll dune registry

- CHANGES.md
- ocaml-lsp-server/src/code_actions.ml
- ocaml-lsp-server/src/code_actions/action_remove_type_annotation.ml
- ocaml-lsp-server/src/code_actions/action_remove_type_annotation.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e-new/code_actions.ml
- ocaml-lsp-server/test/e2e-new/start_stop.ml
> feat(ocamllsp): Code action "Remove type annotation"

- CHANGES.md
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e-new/start_stop.ml
Mentioned in #911.
According to [LSP spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/):
```
/**
* The server provides code actions. The `CodeActionOptions` return type is
* only valid if the client signals code action literal support via the
* property `textDocument.codeAction.codeActionLiteralSupport`.
*/
codeActionProvider?: boolean | [CodeActionOptions](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeActionOptions);
```
When client doesn't support code action literal, we return boolean instead.
I didn't modify returned code actions based on kinds supported by client, because client is supposed to handle actions that it doesn't support:
```
/**
* The client supports code action literals as a …
```
> fix(ocamllsp): Respect codeActionLiteralSupport capability

- .github/workflows/changelog.yml
- README.md
As mentioned in: https://github.com/ocaml/ocaml-lsp/pull/1046#issuecomment-1460659640
We use this action:
https://github.com/tarides/changelog-check-action
> Changelog check

- .github/workflows/changelog.yml
We need to add a `no changelog` label so that this check can be skipped. Unfortunately, I don't have the necessary write access to do it on my own.
> fix: Branch name in changelog check

- CHANGES.md
- ocaml-lsp-server/src/code_actions/action_remove_type_annotation.ml
- ocaml-lsp-server/src/code_actions/action_type_annotate.ml
- ocaml-lsp-server/test/e2e-new/code_actions.ml
As discussed in #801. I've tried to fix it with #1048, but found no reasonable solution.
This PR disables type annotation for functions, which I think is better than allowing users to generate invalid code.
> fix(ocamllsp): Disable type annotation for functions

- CHANGES.md
- ocaml-lsp-server/src/semantic_highlighting.ml
Hello,
This PR follows up and solves issue #1034 where usage of preprocessors breaks semantic highlighting.
After a few minutes of investigation with @thierry-martinez we saw that, in order to parse long identifiers (e.g. `Foo.Bar.x`), ocaml-lsp reads again the source pre-preprocessor (`raw_source`) to semantic highlight the tokens in long identifiers (following PR #932).
The problem is that locations in the AST do not correspond to the ones in `raw_source`, but to the ones in `source`.
I'm not sure this modification could cause issues, but this source is only used to retrieve the source code of long identifiers. All tests still pass.
> fix(semantic highlighting): use preprocessed source to highlight long identifiers

- CHANGES.md
- lsp/src/cli.ml
- lsp/src/cli.mli
- ocaml-lsp-server/bin/main.ml
It does nothing for now, but it's in the standard so it's better to at
least explicitly ignore it.
> feature: support --clientProcessId argument

- CHANGES.md
- lsp/src/cli.ml
- lsp/src/cli.mli
- ocaml-lsp-server/bin/main.ml
cc @ddickstein. The spec is quite confusing about this:
> socket: uses a socket as the communication channel. The port is passed as next arg or with --port=.
So I believe that makes `--port` a synonym.
> feature: add --port as a synonym to --socket

- ocaml-lsp-server/test/e2e/__tests__/textDocument-signatureHelp.ts
To merge before #1088 to show the difference in the ocamldoc syntax support.
A few issues are demonstrated in the test:
- Lacking support for module list
- Titles are not put in a new line
- Labels in titles are not supported
> test(ocamllsp): ocamldoc markdown conversion

- lsp/src/text_document.ml
- lsp/src/text_document.mli
- lsp/test/text_document_tests.ml
Text_document.absolute_{position,range} are used to extract absolute
positions in the string.
> feature(lsp): api for absolute positions

- lsp-fiber/src/fiber_io.ml
- lsp/src/io.ml
- lsp/src/io.mli
So that we don't have to assume that writes aren't interleaved.
cc @ddickstein
> fix(lsp): make write take list of strings

- lsp/src/text_document.ml
- lsp/src/text_document.mli
> refactor(lsp): remove Text_document.Expert

- ocaml-lsp-server/src/ocaml_lsp_server.ml
Logging message claims that we ignore cancellation. That is not the case
and we handle it in both rpc.ml and the individual requests that care
about it.
> refactor: remove incorrect logging message

- lsp/src/client_notification.ml
- lsp/src/client_notification.mli
- lsp/src/server_notification.ml
- lsp/src/server_notification.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
It's sent by the server to the client rather than the other way around.
> fix(lsp): move LogTrace to the correct location

- CHANGES.md
- README.md
- ocaml-lsp-server/docs/ocamllsp/config.md
- ocaml-lsp-server/src/config_data.ml
- ocaml-lsp-server/src/configuration.ml
- ocaml-lsp-server/src/configuration.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e-new/workspace_change_config.ml
This PR add support to enable/disable settings through `didChangeConfiguration` notification.
- CodeLens
- Extended Hover
```lua
require('lspconfig').ocamllsp.setup {
cmd = {'ocamllsp'},
on_attach = on_attach,
settings = {
extendedHover = { 
enable = true 
},
codelens = {
enable = false
}
},
capabilities = capabilities,
}
```
Close #1102
> support settings through `didChangeConfiguration` notification

- .github/workflows/nix.yml
Addressing CI warning:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: cachix/install-nix-action@v15. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> Bump install-nix-action

- lsp/bin/metamodel/metaModel.json
- lsp/src/types.ml
- lsp/src/types.mli
Rather than "string". This was a bug in the metamodel.json we were using
> fix(lsp): type of target is URI

- ocaml-lsp-server/src/merlin_config.ml
> refactor: simplify file existence check

- flake.lock
- flake.nix
Use nixpkgs instead of opam-nix by default.
It's far faster and does everything we need.
> refactor: switch to nixpkgs

- lsp/src/client_request.ml
- lsp/src/client_request.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
> feature(lsp): add InlayHint client request

- ocaml-lsp-server/src/import.ml
> refactor: clean up imports of merlin

- CHANGES.md
- ocaml-lsp-server/src/merlin_config.ml
kill didn't use to work because of buggy versions of `dune ocaml-version`. Those have been fixed, so sigterm should work fine.
> fix: kill dune ocaml-merlin in a friendlier way

- CHANGES.md
- ocaml-lsp-server/src/ocamlformat_rpc.ml
if [get_process] is alled concurrently, the ivar might be filled twice.
Fixes #1115
> fix: ocamlformat-rpc initialization

- CHANGES.md
- ocaml-lsp-server/docs/ocamllsp/config.md
- ocaml-lsp-server/src/config_data.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-codeLens.test.ts
This feature seems to annoy quite a few users so we disable it by
default. It can be enabled through configuration.
> feature: disable code lens by default

- CHANGES.md
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e-new/dune
- ocaml-lsp-server/test/e2e-new/for_pp.ml
- ocaml-lsp-server/test/e2e-new/for_pp.sh
- ocaml-lsp-server/test/e2e-new/with_pp.ml
Hello,
In the PR that made Merlin a dependency #1070 a bug was introduced that prevents from using preprocessor programs as https://github.com/ocaml-community/cppo.
This is because the file permissions are not provided in the right base and that the output files are currently not created if they do not exist yet.
I do not know if the addition of the flag `Unix.O_CREAT` could cause an issue with some pp or ppx.
> fix(ocamllsp): fix in pp handling the file permissions

- flake.nix
Fixes `nix run`.
Before:
```
[rafal@nixos ocaml-lsp]$ nix run
error: unable to execute '/nix/store/pvlaay6869p70xsgkj2cj942ay3jvjiz-ocaml4.14.1-ocaml-lsp-server-n-a/bin/ocaml-lsp-server': No such file or directory
```
After:
```
[rafal@nixos ocaml-lsp]$ nix run . -- --help
ocamllsp [ --stdio | --socket PORT | --port PORT | --pipe PIPE ] [ --clientProcessId pid ]
--version print version
--fallback-read-dot-merlin read Merlin config from .merlin files. The `dot-merlin-reader` package must be installed
--pipe set pipe path
--socket set the port
--port synonym for --socket
--stdio set stdio
--node-ipc not supported
--clientProcessId set the pid of the lsp client
-help  Display this list of options
--help  Display this list of options
```
> fix: Nix mainProgram name

- ocaml-lsp-server/test/e2e-new/dune
shell scripts cannot be executed like binaries
> chore: windows tests

- CHANGES.md
- ocaml-lsp-server/src/doc_to_md.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-signatureHelp.ts
This PR does not add support for cross-references, but Doc_to_md now outputs the text of the reference, instead of a line break as it does currently.
> Display text of references in doc strings

- CHANGES.md
- ocaml-lsp-server/src/doc_to_md.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/ocaml_lsp_server.mli
- ocaml-lsp-server/test/e2e-new/doc_to_md.ml
- ocaml-lsp-server/test/e2e-new/dune
- ocaml-lsp-server/test/e2e-new/with_pp.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-signatureHelp.ts
> retain super/subscripts in markdown conversion

- CHANGES.md
- ocaml-lsp-server/src/merlin_config.ml
Fix #859.
For background, internally at Meta we use [buck2](https://buck2.build/) to build ocaml code, and we have a script to automatically generate a .merlin file based on the build artifacts. I'm not asking for a buck2 integration here. I'm simply fix the issue that blocks us from switching away from the long dead `ocaml-language-server`.
I find that the flag doesn't work if the environment does not have dune installed, because it will unconditionally run some dune command before even checking the `--fallback-read-dot-merlin` flag. This PR moves the check earlier, so that when the flag is on, it fully bypasses the dune workflow.
> Do not invoke dune at all if `--fallback-read-dot-merlin` flag is on

- CHANGES.md
- ocaml-lsp-server/src/semantic_highlighting.ml
- ocaml-lsp-server/test/e2e-new/semantic_hl_tests.ml
> Fix semantic highlighting of infix operators

- CHANGES.md
- ocaml-lsp-server/src/code_actions/action_type_annotate.ml
Occurrence is in `type-annotate` code action.
Same as https://github.com/ocaml/ocaml-lsp/pull/1191
> Only return first result for type_enclosing.

- ocaml-lsp-server/src/progress.ml
removes the incomplete pattern match warning on the progress
> refactor: fix against newer versions of dune

- CHANGES.md
> chore: more CHANGES formatting

- dune-project
- ocaml-lsp-server.opam
we aren't compatible with 2.3.0
> fix: odoc-parser constraints

- CHANGES.md
- lsp/src/uri0.ml
- lsp/test/uri_tests.ml
The current implementation is not the same as `uri.ts`
see https://github.com/microsoft/vscode-uri/blob/96acdc0be5f9d5f2640e1c1f6733bbf51ec95177/src/uri.ts#L601
the ts code just checks if authority is empty, while ocaml code checks if authority is "file"
> Fix uri to_string

- CHANGES.md
- dune-project
- flake.nix
- ocaml-lsp-server.opam
- ocaml-lsp-server/src/doc_to_md.ml
- ocaml-lsp-server/src/dune
- ocaml-lsp-server/test/e2e-new/doc_to_md.ml
- vendor/odoc-parser/LICENSE
- vendor/odoc-parser/src/ast.ml
- vendor/odoc-parser/src/compat.ml
- vendor/odoc-parser/src/compat.mli
- vendor/odoc-parser/src/dune
- vendor/odoc-parser/src/lexer.mli
- vendor/odoc-parser/src/lexer.mll
- vendor/odoc-parser/src/loc.ml
- vendor/odoc-parser/src/loc.mli
- vendor/odoc-parser/src/odoc_parser.ml
- vendor/odoc-parser/src/odoc_parser.mli
- vendor/odoc-parser/src/parse_error.ml
- vendor/odoc-parser/src/syntax.ml
- vendor/odoc-parser/src/syntax.mli
- vendor/odoc-parser/src/token.ml
- vendor/odoc-parser/src/warning.ml
- vendor/update-odoc-parser.sh
This PR makes ocaml-lsp compatible with the soon release odoc-parser.2.3.0
odoc-parser adds two new constructs:
- "Outputs" of code blocks. This is meant to be generated by the code blocks and promoted by mdx.
- Tables
Tables are tricky, as odoc tables are allowed to have some block content inside ("nestable" block contents) while markdown is not.
This means that when translating odoc tables into cmarkit tables, we need to turn blocks into inlines. This issue is responsible for most of the code of the PR!
> Compatibility with odoc-parser.2.3.0

- CHANGES.md
- ocaml-lsp-server/docs/ocamllsp/config.md
- ocaml-lsp-server/src/config_data.ml
- ocaml-lsp-server/src/configuration.ml
- ocaml-lsp-server/src/configuration.mli
- ocaml-lsp-server/src/diagnostics.ml
- ocaml-lsp-server/src/diagnostics.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
I like to work with incomplete files a lot and playing around with them before actually saving, going through many intermediary steps.
But due to how OCaml LSP behaves as soon as you save a file with a single error coming from dune, that error will be there until you save it again, which is quite annoying.
So I've been using for almost 2 years a patched version of the OCaml LSP without dune diagnostics, this is hopefully that but as an opt-in option.
I tried to make the patch the least invasive, keeping all the features except the dune reporting inside of files, to do that I disable the **entire diagnostics loop**, this may be too much, but in the last years I never detected any issues.
```json
{
"ocaml.sandbox": {
"kind": "global"
},
"ocaml.server.args": [
"--no-dune-diagnostics"
]
}
``` …
> Add flag to disable dune diagnostics

- CHANGES.md
- ocaml-lsp-server/src/folding_range.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-foldingRange.test.ts
Support folding ranges for `ifthenelse` expressions. 
Before:
https://user-images.githubusercontent.com/5595092/218944712-f71cbd25-ae60-410f-8bd1-f1c06394b2f5.mov
After:
https://user-images.githubusercontent.com/5595092/218944755-c5fb89cf-5d74-4279-8af8-d23091fab810.mov
As you can see in the video above, we can collapse the entire `if` expression but not the `else`. This is because we don't have the start location of the `else` keyword. We only have the location of the whole `expression` inside the `else`. We can add this location to the ranges, but it doesn't appear next to the `else`.
https://user-images.githubusercontent.com/5595092/218945059-2f85fb6b-8536-4afd-9c6f-a8b05c5c10f4.mov
Also, it makes it impossible to collapse only the first expression inside the `else`.
> feat(ocamllsp): support Pexp_ifthenelse folding ranges

- CHANGES.md
- ocaml-lsp-server/src/code_actions.ml
- ocaml-lsp-server/src/code_actions/action_open_related.ml
- ocaml-lsp-server/src/code_actions/action_open_related.mli
- ocaml-lsp-server/src/custom_requests/req_switch_impl_intf.ml
- ocaml-lsp-server/src/custom_requests/req_switch_impl_intf.mli
- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/document.mli
- ocaml-lsp-server/src/inference.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
Currently doc kind (impl vs intf) is hardcoded as a set of file extensions.
Instead this PR tried to get kind info from merlin first, and if it fails, fallback to the old way.
Ref: https://github.com/ocaml/dune/pull/8567
> refactor: get doc kind info from merlin

- ocaml-lsp-server/test/e2e-new/dune
- ocaml-lsp-server/test/e2e-new/exit_notification.ml
- ocaml-lsp-server/test/e2e-new/test.ml
As requested in https://github.com/ocaml/ocaml-lsp/pull/1239#issuecomment-2061097336.
It seems that the `ocamllsp` server behaves according to the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#exit), except for the case where `Exit` is sent without a previous `Shutdown`, in which case it exits with code 0, but it should be 1.
> test: add tests for exit and shutdown notifications

- CHANGES.md
- ocaml-lsp-server/src/hover_req.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e-new/with_ppx.ml
This PR makes several changes to hover behavior to reduce overly noisy hovers, and adds hovering on some PPXes to see the PPX expansion.
The LSP currently provides hovers in many places that are unhelpful and noisy, including on comments and many keywords. 
This patch, instead of providing a hover on every position where `Document.Merlin.type_enclosing` returns a result, uses the `hover_at_cursor` function to iterate over the parsetree and select the subset of nodes where hover information is useful.
The primary impact of this is the LSP no longer provides hovers on whitespace, comments, or most keywords and punctuation.
The `TextDocumentHighlight` request can highlight very large ranges in a way that's distracting and not helpful.
This happens frequently with some PPXes.
This PR adds …
> Improving hover behavior

- CHANGES.md
- ocaml-lsp-server/src/check_for_comments.ml
- ocaml-lsp-server/src/check_for_comments.mli
- ocaml-lsp-server/src/compl.ml
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/signature_help.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-signatureHelp.ts
When the user requests signature help or completions via a trigger character, do not provide a repsonse if the request was generated from within a comment. This reduces unhelpful noise when writing comments.
> Disable trigger-character completions and signature help in comments

- submodules/lev/lev-fiber/src/lev_fiber.ml
running the scheduler more than once no longer leaks fd's
> fix(lev-fiber): scheduler fd leak

- flake.nix
> chore(nix): fmt

- flake.lock
- flake.nix
Also set a custom source for merlin as it's something we very often need to change.
> chore(nix): allow overriding ocaml version

- .ocamlformat
- CHANGES.md
- ocaml-lsp-server/src/document_symbol.ml
- ocaml-lsp-server/src/document_symbol.mli
- ocaml-lsp-server/src/workspace_symbol.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-documentSymbol.ts
Produce a much more detailed set of document symbols in the LSP.
Since this now uses the reader parse-tree only, it will work equally well even when not building a given file.
The important highlights are:
- Include symbols to arbitrary depth (i.e. nested variables / functions)
- Differentiate functions / types / variants / etc
- This now includes PPXs like `let%expect_test` or `let%bench` in the outline
Some functions were also used by workspace-symbols, and the relevant functions are moved to that file instead.
> Improved document symbols

- CHANGES.md
- README.md
- dune-project
- ocaml-lsp-server.opam
- ocaml-lsp-server/docs/ocamllsp/config.md
- ocaml-lsp-server/src/config_data.ml
- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/document.mli
- ocaml-lsp-server/src/hover_req.ml
- ocaml-lsp-server/test/e2e-new/dune
- ocaml-lsp-server/test/e2e-new/syntax_doc_tests.ml
This PR introduces a new feature to OCaml-LSP for both beginners and also more experienced programmers. No more searching for obscure keywords or symbols on Google trying to find documentation. 
With this PR, you can hover over OCaml code in your editor, and instantly see a clear and summarized explanation of its syntax along with a link to the exact portion of OCaml's documentation for it.
- Faster understanding: At a glance you can get a quick description of what the syntax is about.
- Improved learning: Beginners can easily understand how their code works while writing the code.
- Enhanced productivity: Very useful for understanding codebases and what a syntax is supposed to do.
- Hover your cursor over the OCaml code.
- The hover request will call the new `Syntax Documentation` …
> Demystifying OCaml Syntax with Merlin and OCaml-LSP

- ocaml-lsp-server/src/code_actions.ml
- ocaml-lsp-server/src/code_actions/action_destruct.ml
- ocaml-lsp-server/src/custom_requests/req_typed_holes.ml
- ocaml-lsp-server/src/custom_requests/req_wrapping_ast_node.ml
- ocaml-lsp-server/src/definition_query.ml
- ocaml-lsp-server/src/document.ml
- ocaml-lsp-server/src/document.mli
- ocaml-lsp-server/src/hover_req.ml
- ocaml-lsp-server/src/inference.ml
- ocaml-lsp-server/src/inlay_hints.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/rename.ml
- ocaml-lsp-server/src/signature_help.ml
Add names to all merlin pipelines that currently lack a name. This is helpful for implementing telemetry—Jane Street's internal ocaml-lsp telemetry uses these names. This PR should have no impact otherwise.
> name all merlin pipelines

- CHANGES.md
- ocaml-lsp-server/src/compl.ml
- ocaml-lsp-server/test/e2e-new/action_inline.ml
- ocaml-lsp-server/test/e2e-new/completion.ml
- ocaml-lsp-server/test/e2e-new/completions.ml
- ocaml-lsp-server/test/e2e-new/dune
- ocaml-lsp-server/test/e2e-new/helpers.ml
- ocaml-lsp-server/test/e2e-new/helpers.mli
- ocaml-lsp-server/test/e2e-new/hover_extended.ml
- ocaml-lsp-server/test/e2e-new/workspace_change_config.ml
For completions on labels that the LSP gets from merlin, take into account whether the prefix being completed starts with `~` or `?`.
Merlin appears to always returns the full set of labeled/optional arguments when asked for completions. The LSP forwards these on, leaving it to the client to filter them. The  problem is that merlin supplies the optional argument completions with a leading `?` regardless of the prefix the user typed. This causes the client to either filter them out (VSCode) or offer completions that might flip an optional argument being passed with `~` to one passed with `?` (Emacs). 
This PR changes the label completions that start with `?` to start with `~` when the prefix being completed starts with `~`. It also adds a test case and does a bit of refactoring of test …
> respect completion prefix when completing optional arguments

- lsp/src/string_zipper.ml
- lsp/test/string_zipper_tests.ml
fix book-keeping of [abs_pos] in [String_zipper.goto_line_backward]
> fix(lsp): goto_line_backward abs_pos

- CHANGES.md
- lsp/src/string_zipper.ml
- lsp/test/text_document_tests.ml
- ocaml-lsp-server/test/e2e-new/action_mark_remove.ml
This PR should fix a problem that occurs when editing a text document with `apply_text_document_edits`, where some text could be duplicated, as shown in #1207.
> Fix abs_pos computing in `String_zipper.drop_until`

- flake.nix
> chore(nix): some cleanups

- CHANGES.md
- dune-project
- flake.nix
- ocaml-lsp-server.opam
- ocaml-lsp-server/src/code_actions.ml
- ocaml-lsp-server/src/code_actions/action_destruct.ml
- ocaml-lsp-server/src/code_actions/action_destruct_line.ml
- ocaml-lsp-server/src/code_actions/action_destruct_line.mli
- ocaml-lsp-server/src/dune
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/test/e2e-new/code_actions.ml
- ocaml-lsp-server/test/e2e-new/start_stop.ml
Merlin-destruct is made more useful by adding a new LSP code-action called `destruct-line` which does some pre- and post-processing surrounding a call to Merlin-destruct.
This new code-action can be invoked on a line where the user has typed `match...` or `match...with`, or within an incomplete match statement on a line with an existing case. When invoked, the code-action will fill in the remaining cases of the match. This means that in VSCode, if you have one of the following lines, you can hit `C-.` from anywhere on the line to achieve the corresponding expansion.
Supposing `x` is a `bool`, then the line
```ocaml
match x
```
expands to
```ocaml
match x with
| false -> _
| true -> _
```
Supposing `get_card` returns a `card_value` variant, then the line
```ocaml
match get_card …
```
> Add new destruct-line code action

- CHANGES.md
- ocaml-lsp-server/src/inlay_hints.ml
Inlay hints are both noisy and useless when applied to generated code. Examples include lots of unnecessary hints on the fields of a record definition that derives things like `sexp` or `fields`, or confusing annotations on format strings using `!`. 
All the generated code exists under typedtree nodes with ghost locations. This PR changes the inlay hint logic to stop iterating over the typedtree when it sees an expression or a structure item with a ghost location.
> Disable inlay hints under ghost location

- CHANGES.md
- ocaml-lsp-server/src/signature_help.ml
Fix the algorithm that decides when to wrap a signature hint with parens.
Testing
-------
Ran the LSP locally and confirmed this correctly surrounds function argument types with parens.
> Fix parens around function types in signature help

- ocaml-lsp-server/src/code_actions/action_destruct_line.ml
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/test/e2e-new/code_actions.ml
Fixed a bug where destruct-line would sometimes fail to provide the "-> _" on the
right-hand side of cases when Merlin split its response across multiple lines.
Used the opportunity to clean up how the reply gets formatted: it now relies on fewer
fragile regular expressions and should generally be a bit easier to read.
Testing also led to the discovery of some bad behavior on case-lines where the lhs is
a hole, but the cursor isn't on the hole. This was fixed by adding `OffsetHole` to the
`statement_kind` variants.
Testing
-------
Updated the expect-tests for long variant names, offset-holes, and hole-spacing.
Importantly, the tests called "destruct strips parentheses even on long lines" and
"destruct a case with a hole but not on the hole" confirm the bug-fixes.
> bug fixes for destruct-line edge cases

- CHANGES.md
- ocaml-lsp-server/src/hover_req.ml
- ocaml-lsp-server/test/e2e-new/syntax_doc_tests.ml
- ocaml-lsp-server/test/e2e/__tests__/ocamllsp-hoverExtended.ts
- ocaml-lsp-server/test/e2e/__tests__/textDocument-hover.test.ts
vscode renderer treats the section before a `---` divider as a title (it is a [setext heading](https://spec.commonmark.org/0.31.2/#setext-heading-underline), see [example 59](https://spec.commonmark.org/0.31.2/#example-59)). This stayed undetected before the syntax doc PR because only code was printed before the divider.
Current behavior with `---`:
We can use stars to get a delimiter without a heading:
cc @PizieDust
> hover: use `***` to print dividers.

- CHANGES.md
- ocaml-lsp-server/docs/ocamllsp/typeEnclosing-spec.md
- ocaml-lsp-server/src/custom_requests/req_type_enclosing.ml
- ocaml-lsp-server/src/custom_requests/req_type_enclosing.mli
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e-new/dune
- ocaml-lsp-server/test/e2e-new/start_stop.ml
- ocaml-lsp-server/test/e2e-new/type_enclosing.ml
This PR is based on [1265](https://github.com/ocaml/ocaml-lsp/pull/1265) and add a `type enclosing` custom request.
> Type enclosing query

- Makefile
- ocaml-lsp-server/test/e2e-new/helpers.ml
- ocaml-lsp-server/test/e2e-new/test.ml
@xvw your original is still flaky even with your workaround. Your workaround also makes the tests way slower for everyone. Let's keep the test suite in a healthy state.
> chore: revert incorrect changes to Makefile

- lsp/src/server_request.ml
- lsp/src/server_request.mli
> feature: add missing server requests

- ocaml-lsp-server/src/doc_to_md.ml
move bindings closer to uses and reduce scope
> refactor: doc_to_md

- ocaml-lsp-server/src/custom_requests/custom_request.ml
- ocaml-lsp-server/src/custom_requests/custom_request.mli
- ocaml-lsp-server/src/custom_requests/req_hover_extended.ml
- ocaml-lsp-server/src/custom_requests/req_hover_extended.mli
- ocaml-lsp-server/src/custom_requests/req_merlin_call_compatible.ml
- ocaml-lsp-server/src/custom_requests/req_merlin_call_compatible.mli
- ocaml-lsp-server/src/custom_requests/req_type_enclosing.ml
- ocaml-lsp-server/src/custom_requests/req_type_enclosing.mli
- ocaml-lsp-server/src/custom_requests/req_typed_holes.ml
- ocaml-lsp-server/src/custom_requests/req_typed_holes.mli
- ocaml-lsp-server/src/custom_requests/req_wrapping_ast_node.ml
- ocaml-lsp-server/src/custom_requests/util.ml
- ocaml-lsp-server/src/custom_requests/util.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/ocaml_lsp_server.mli
- ocaml-lsp-server/test/e2e-new/merlin_call_compatible.ml
- ocaml-lsp-server/test/e2e-new/test.ml
- ocaml-lsp-server/test/e2e-new/type_enclosing.ml
The patch proposes a global pass on Custom Requests by trying to impose the `module Request_params` structure, which proposes a creation function (and projection in Yojson), and a `type t` at the module toplevel (with a conversion function from Yojson). 
- What's more, parameter deserialization relies on Yojson's API to get close to what derivation would give.
- The `Custom_request` module is exposed by `Ocaml_lsp_server` for use from, for example, tests (and also from a JavaScript client, ie: vscode).
- Some requests have been modified very little to avoid introducing breaking-changes.
I'm obviously open to feedback!
> Global pass on Custom_request

- README.md
Opam should automatically choose the latest supported OCaml version.
Fixes #1356
> Remove the fixed OCaml version in dev instructions

- CHANGES.md
- ocaml-lsp-server/src/prefix_parser.ml
- ocaml-lsp-server/test/e2e-new/completion.ml
When completing method access like in `my_object#a|` Merlin expect the "prefix" to be `a` and not `myobject#a` as it would be for accessing a record field. 
This PR introduces a special case in the parsing of prefixes.
Additionally I found the `in` keyword completion a bit too aggressive and removed on of the cases. @ulugbekna do you remember why you made completions with an empty prefix always suggest the `in` keyword ?
> Fix prefix parsing to start method completion when typing `#`

- CHANGES.md
- ocaml-lsp-server/docs/ocamllsp/construct-spec.md
- ocaml-lsp-server/src/custom_requests/custom_request.ml
- ocaml-lsp-server/src/custom_requests/custom_request.mli
- ocaml-lsp-server/src/custom_requests/req_construct.ml
- ocaml-lsp-server/src/custom_requests/req_construct.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e-new/construct.ml
- ocaml-lsp-server/test/e2e-new/dune
- ocaml-lsp-server/test/e2e-new/start_stop.ml
At the moment, construct is a completion hook, and in some cases accessing it via a one-off query can be useful.
> Construct custom query

- ocaml-lsp-server.opam
- ocaml-lsp-server/src/inference.ml
- ocaml-lsp-server/src/inlay_hints.ml
- ocaml-lsp-server/src/signature_help.ml
This brings together changes from [#1366](https://github.com/ocaml/ocaml-lsp/pull/1366), https://github.com/ocaml/ocaml-lsp/pull/1367 and https://github.com/ocaml/ocaml-lsp/pull/1375.
We now rely on `merlin-lib` implementations for inlay-hint and signature help.
> Rely on upstream Merlin analyses

- dune-project
Merlin lib version was bumped in the opam file but not in the dune-project.
> Bump merlin-lib version

- CHANGES.md
- ocaml-lsp-server/docs/ocamllsp/config.md
- ocaml-lsp-server/src/code_actions.ml
- ocaml-lsp-server/src/code_actions/action_jump.ml
- ocaml-lsp-server/src/config_data.ml
- ocaml-lsp-server/test/e2e-new/code_actions.ml
This PR aims to fix some of the issues related to the Jump code actions. 
cc @voodoos @xvw @rgrinberg @awilliambauer
> Update Jump Code actions

- lsp/src/uri0.ml
- lsp/src/uri0.mli
- lsp/src/uri_lexer.mli
- lsp/src/uri_lexer.mll
- lsp/test/uri_tests.ml
This is useful because in VSCode, file system URIs can contain line numbers in the fragment: `file:///path#N`.
> Add support for URI fragments

- CHANGES.md
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-selectionRange.test.ts
@awilliambauer @pitag-ha I looked at the server answer to the `selectionRange` query after our discussion earlier today, and I noticed that they were, in fact, duplicated ranges:
```
[Trace - 17:40:29] Received response 'textDocument/selectionRange - (20)' in 6ms.
Result: [
{
"parent": {
"parent": {
"parent": {
"parent": {
"parent": {
"parent": {
"parent": {
"parent": {
"parent": {
"parent": {
"range": {
"end": {
"character": 38,
"line": 968
},
"start": {
"character": 0,
"line": 0
}
}
},
"range": {
"end": {
"character": 26,
"line": 409
},
"start": {
"character": 0,
"line": 379
}
}
},
"range": {
"end": {
"character": 26,
"line": 409
},
"start": {
"character": 0,
"line": 379
}
}
},
"range": {
"end": {
"character": 26,
"line": 409
},
"start": {
"character": 2,
"line": 380
}
}
},
...
"range": …
```
> selection_range: use merlin enclosing query instead of shape

- CHANGES.md
- ocaml-lsp-server/src/code_actions.ml
In some cases these can make the `codeAction` request slow (>2s).
> Disable jump code action by default

- CHANGES.md
- ocaml-lsp-server/src/config_data.ml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/test/e2e-new/code_actions.ml
- ocaml-lsp-server/test/e2e-new/lsp_helpers.ml
- ocaml-lsp-server/test/e2e-new/lsp_helpers.mli
- ocaml-lsp-server/test/e2e-new/syntax_doc_tests.ml
As far as I know it is not possible to disable the default hover provider on the client side in vscode due to how the official LSP client implementation manage it.
However it is sometimes necessary to disable that hover provider to provide alternative information in the hover tooltips without additional clutter.
This PR introduces an option that allows the client to ask the server to not return anything when hover requests are made.
The diff is a bit larger than necessary because `dune build @lint` had not been run when options when last updated so the inlining has changed a bit.
The first use case for this option is described in this vscode-ocaml-platform PR: https://github.com/ocamllabs/vscode-ocaml-platform/pull/1675
> Add a new option to mute the hover response.

- CHANGES.md
- ocaml-lsp-server/src/import.ml
- ocaml-lsp-server/src/rename.ml
- ocaml-lsp-server/test/e2e/__tests__/textDocument-rename.test.ts
This introduces a first functional version of project-wide renaming in ocaml-lsp based on [preview work](https://github.com/ocaml/merlin/pull/1877) on Merlin.
It re-employs the existing mechanism to handle function labelled arguments correctly. There is no guarantees related to possible shadowing. Here is an example of the feature in action, renaming a value of a functor included from its parameter. The name is changes in all the files, both in signatures and implementations, and the project rebuilds immediately:
https://github.com/user-attachments/assets/8608b5f9-6102-4a39-a808-c9d7b642c8ee
This PR is based on #1386 and only the last 2 commits are relevant.
> Introduce project-wide renaming

- CHANGES.md
- ocaml-lsp-server/src/document_symbol.ml
- ocaml-lsp-server/test/e2e-new/document_symbol.ml
- ocaml-lsp-server/test/e2e-new/dune
> Add support for class, class types and methods in DocumentSymbol

- .github/workflows/build-and-test.yml
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/rename.ml
This PR goes along with https://github.com/ocaml/merlin/pull/1885, which changes Merlin's api for occurrences requests to include more staleness information.
> Stale occurrences

- CHANGES.md
- ocaml-lsp-server/src/config_data.ml
- ocaml-lsp-server/src/inlay_hints.ml
- ocaml-lsp-server/test/e2e-new/inlay_hints.ml
This PR needs https://github.com/ocaml/merlin/pull/1923 (on merlin's side) to works
(cc @awilliambauer)
> Add `hintFunctionParams` inlay hints

- CHANGES.md
- ocaml-lsp-server/src/definition_query.ml
In order to have best diagnostics at the editor level.
> Handle error cases in `definition_query`

- CHANGES.md
- ocaml-lsp-server/src/code_actions/action_destruct.ml
- ocaml-lsp-server/test/e2e-new/code_actions.ml
Formatting on `destruct` is rarely useful: 
- when it generate cases, it fails (and it relay on the non-formatted case)
- when merlin return a result with parenthesis, since ocamlformat is not aware about the context, it remove parenthesis (making a lot of `destruct results` not insertable, which is very sad).
> Remove formatting in code action destruct

- CHANGES.md
- ocaml-lsp-server/src/code_actions.ml
- ocaml-lsp-server/src/code_actions/action_combine_cases.ml
- ocaml-lsp-server/src/code_actions/action_combine_cases.mli
- ocaml-lsp-server/test/e2e-new/code_actions.ml
The combine-cases code action allows the user to select several one-line cases of a match and combine them into a single one-line case. If there is a unique non-empty right-hand-side expression it will be preserved; otherwise the RHS will be a hole.
For example, if the user highlights the King and Queen lines of the following snippet and invokes combine-cases:
```ocaml 
match card with
| Ace -> _
| King -> _
| Queen -> "Face card!"
| Jack -> "Face card?"
| Number _ -> _
```
then the code action will update the snippet to:
```ocaml
match card with
| Ace -> _
| King | Queen -> "Face card!"
| Jack -> "Face card?"
| Number _ -> _
```
If instead (or afterwards) they invoke combine-cases highlighting the King, Queen, and Jack lines, they'll get:
```ocaml
match card with
| Ace -> _
| King | …
```
> Add code action combine cases

- CHANGES.md
- ocaml-lsp-server/src/config_data.ml
- ocaml-lsp-server/src/configuration.ml
- ocaml-lsp-server/src/configuration.mli
- ocaml-lsp-server/src/diagnostics.ml
- ocaml-lsp-server/src/diagnostics.mli
- ocaml-lsp-server/src/ocaml_lsp_server.ml
- ocaml-lsp-server/src/range.ml
- ocaml-lsp-server/src/range.mli
- ocaml-lsp-server/src/testing.ml
- ocaml-lsp-server/test/e2e-new/diagnostics_filter.ml
- ocaml-lsp-server/test/e2e-new/dune
- ocaml-lsp-server/test/e2e-new/lsp_helpers.ml
- ocaml-lsp-server/test/e2e-new/lsp_helpers.mli
Make error diagnostics shortenable (to improve readability)
> Shorten Merlin diagnostics error

- CHANGES.md
- lsp/src/import.ml
Changed `Nullable_option.yojson_of_t` to serialize `None` as `Null` instead of asserting false.
Fixes #1524
> Correct nullable_option serialization

- submodules/lev/lev/src/config.h
fixes https://github.com/ocaml/ocaml-lsp/issues/1459
> 414 lts freebsd
